radixdlt/babylon-wallet-ios

Sources/Clients/ProfileStore/ProfileStore.swift, Sources/Profile/AppPreferences/AppPreferences.swift, Sources/Profile/AppPreferences/Gateways/Gateways.swift, Sources/Profile/Snapshot/ProfileSnapshot.swift
Jira ticket: [ABW-2378](https://radixdlt.atlassian.net/browse/ABW-2378)
Change current network (gateway) to `.mainnet` after having finished importing a `Profile` (wallet backup data).
General soundness measure, safe to do since all Profiles should contain `.mainnet` accounts. 
You can use [this Profile](https://drive.google.com/file/d/1-4cFc3xfZgu5hJ-Zshq3O90QFh5kh1bF/view?usp=drive_link) (requires RDX Works account)
Mnemonic is:
```
anger dizzy pond category scissors broccoli earth royal palace intact fox engage mix area engage right argue derive promote control hard order silver wait
```
[ABW-2378]: https://radixdlt.atlassian.net/browse/ABW-2378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2378] Set current gateway to mainnet after import

Sources/Clients/GatewayAPI/GatewayAPIClient+Extension.swift
Fixes the issue when the stakes where not visible if those are fetched from the GW in the second page of resources.
=> Add explicit metadata when loading resource pages

Sources/Features/AccountListFeature/Coordinator/AccountList+View.swift, Sources/Features/SettingsFeature/AccountSecurity/AccountSecurity+Reducer.swift, Sources/Features/SettingsFeature/Settings+Reducer.swift
Jira ticket: [ABW-2231](https://radixdlt.atlassian.net/browse/ABW-2231)
- A: After finishing importing Olympia accounts, the "Go to Account list" button now actually takes us to the home screen
- B: Unrelated issue: Fixed the visual glitch in the home screen where things would get weird if you had many accounts and scrolled to the end (see video)
Still trying to fix the issue where `migratedOlympiaHardwareAccounts` is not being received.
A:
- Import Olympia accounts through the QR process
- When done, press the _Go to account list_ button
-> This should take you back to the home screen
B:
- Have lots of accounts, 10-20
- Scroll to the bottom of the account list in the home screen
-> The scroll view should bounce off the end, and it should not glitch
**B: Scrolling glitch:**
Before: …
=> [ABW-2231] Go To Account List After Olympia Import

Sources/Core/SharedModels/Assets/AccountPortfolio.swift, Sources/Features/AssetsFeature/Components/FungibleAssetList/Components/Details/FungibleTokenDetails+View.swift
This could potentially fix the crashes reported on [here](https://rdxworks.slack.com/archives/C03QFAWBRNX/p1695983208070469)
What this PR does is simply to not calculate the redeemable amount for pool units if the total supply is 0, thus avoiding a potential division-by-zero crash.
=> Check non-zero total supply

Sources/Core/DesignSystem/Components/Hint.swift, Sources/Features/AssetsFeature/AssetsView+Reducer.swift, Sources/Features/CreateAccount/Children/NameAccount/NameAccount+View.swift, Sources/Features/TransactionReviewFeature/CustomizeFees/AdvancedFeesCustomization+View.swift, Sources/Features/TransactionReviewFeature/CustomizeFees/AdvancedFeesCustomization.swift
Jira ticket: [ABW-2395](https://radixdlt.atlassian.net/browse/ABW-2395), [ABW-2397](https://radixdlt.atlassian.net/browse/ABW-2397)
The ABW-2397 ticket actually describes the expected behaviour, the tip percentage is an integer so the decimals will be ignored. This PR:
- removes the decimal separator from the keyboard for tip percentage
- validates padding fee and tip percentage entry and turns the textfield border red when invalid
- BUGFIX: accepts localised decimal separator for padding
- BUGFIX: now actually disables the Create account button when the name is too long
- Initiate a transaction
- Go to Customize [fees]
- Tap View Advanced Mode
- Make the padding fee or percentage fee fields empty
-> The text field should look normal but the value should be interpreted as 0
- Enter an …
=> [ABW-2395, ABW-2397] Use keyboard without decimal separator for tip percentage

Sources/Clients/AccountPortfoliosClient/AccountPortfoliosClient+Live.swift, Sources/Features/AssetsFeature/Components/PoolUnitsList/Components/LSUResource/LSUStake+View.swift
Jira ticket: [ABW-1219](https://radixdlt.atlassian.net/browse/ABW-1219)
- Hides the Liquid Stake Unit when the amount is 0
- Hides a stake claim NFT token if it has a stakeClaimAmount that is 0 or nil
- Hides the entire stake entry if it doesn't have anything left visible
- Fixes [the crash](https://rdxworks.slack.com/archives/C03QFAWBRNX/p1695983208070469) experienced by several users with LSUs.
Before:
After:
[ABW-1219]: https://radixdlt.atlassian.net/browse/ABW-1219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-1219] Fix AssetsView crash and filter Liquid Stake Units

Sources/Clients/ProfileStore/ProfileStore.swift, Sources/Clients/SecureStorageClient/SecureStorageClient+Interface.swift, Sources/Clients/SecureStorageClient/SecureStorageClient+Live.swift, Sources/Clients/SecureStorageClient/SecureStorageClient+Test.swift, Sources/Features/AppFeature/App+Reducer.swift
[Jira Ticket - ABW-2410](https://radixdlt.atlassian.net/browse/ABW-2410)
This fixes a critical bug which me and Jacob have encountered in version 1.0.1 and which at least one community member encountered too.
The root cause is that ProfileStore's `managedAtomicLazyRef` ensures that only ever on Profile is used, HOWEVER, the deviceIdentifiers being saved into keychain could be out of sync, since each new ephemeral profile called `loadDeviceIdentifier` which generated and saved one if nil. If two different tasks called `loadDeviceIdentifier` simulatneously which is the case, then it might be so that the deviceIdentifier of Profile `Q` was saved in keychain as deviceIdentifier, but the Profile `P` was commited and used, where Q.header.lastUsedOnDevice.id != P.header.lastUsedOnDevice.id`, …
=> [ABW-2410] Fix bug where app was in invalid state - discrepancy between Profile.header.lastUsedOnDevice.id and deviceID saved in keychain

Sources/Clients/GatewayAPI/GatewayAPIClient+Extension.swift, Sources/Clients/GatewayAPI/GatewayAPIClient/GatewayAPIClient+Interface.swift, Sources/Core/SharedModels/Assets/AssetBehavior.swift, Sources/Features/AssetsFeature/Components/HelperViews/AssetBehaviorsView.swift, Sources/Features/AssetsFeature/Components/PoolUnitsList/Components/LSUResource/LSUStake.swift, Sources/Features/CreateAccount/Coordinator/CreateAccountCoordinator+Models.swift
Jira tickets: [ABW-2158](https://radixdlt.atlassian.net/browse/ABW-2158), [ABW-2417](https://radixdlt.atlassian.net/browse/ABW-2417)
- ABW-2417: In certain specific cases, it was not possible to select for transfer Stake Claim NFTs
- ABW-2158: The _Information can be changed_ behavior has now been added
- We now show the navbar when Naming an account after GW change
Name account view, before this fix - it lacks navigation bar:
[ABW-2158]: https://radixdlt.atlassian.net/browse/ABW-2158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ABW-2417]: https://radixdlt.atlassian.net/browse/ABW-2417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2158, ABW-2417] Add Missing Behaviors

Sources/Clients/AccountPortfoliosClient/AccountPortfoliosClient+Live.swift, Sources/Features/AccountListFeature/Components/Row/Row+Reducer.swift, Sources/Features/AccountPreferencesFeature/Children/DevAccountPreferences+Reducer.swift, Sources/Features/HomeFeature/Coordinator/Home.swift
The wallet reloads the account portfolios too often. This PR removes most of the unnecessary reloads, and even more cases where an already fetched portfolio is recreated without fetching.
The next step is probably to move to an architecture where e.g. AccountPortfolioClient emits "events" like `portfolioChange(AccountAddress)` which we subscribe to, instead of a currentValueSubject of the portfolios. This will make it possible to distinguish between the first reading of an already fetched portfolio, and subsequent updates to the data. This is important because `.task` is called not just when a view is first created, but every time it comes back into view, causing us to set up subscriptions too often.
Try everything related to portfolio reloading, making sure that views are automatically …
=> [ABW-2271] Remove spurious portfolio reloading

Sources/EngineKit/RETDecimal+Extensions.swift, Sources/Features/TransactionReviewFeature/TransactionReviewGuarantees/MinimumPercentageStepper/MinimumPercentageStepper.swift, Sources/Features/TransactionReviewFeature/TransactionReviewGuarantees/TransactionReviewGuarantees.swift, Tests/EngineKitTests/DecimalTests.swift
Jira ticket: [ABW-2438](https://radixdlt.atlassian.net/browse/ABW-2438)
- We want to accept numbers starting with a decimal separator (`.1`)
- For the guarantee, we want to save all the decimals the user enters
- Also, the guarantee stepper should work in 1% point increments
- When pressing plus/minus on a number with decimals, it will first go to the nearest higher/lower integer
Example for the last point:
If the number is `12.34` and you press +, the number will change to 13. If you press -, it would change to 12. 
[ABW-2438]: https://radixdlt.atlassian.net/browse/ABW-2438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2438] Parsing Decimals

.github/workflows/cd.yml, .github/workflows/ci.yml
- use M1 macos runners
- don't wait for snyk jobs on build
=> ci: improve performance

DEVELOPMENT.md, SETUP_DEV.md, fastlane/Fastfile, fastlane/README.md
* We don't have to run `bundle exec fastlane ios` we can use only `bundle exec fastlane` now since this PR adds `default_plattform` - and update `SETUP_DEV` guide.
* Remove section in `DEVELOPMENT` which incorrectly stated that we are using many targets, no true since since mono target switch https://github.com/radixdlt/babylon-wallet-ios/pull/842
* Rename fastlane lane `register_new_iphone_device` to just `register_new_device` since it we can run the app on Mac! Using Catalyst, "just works"! N.B. **no build settings have changed at all, Catalyst is working on `main` branch already...,**
* Update GH release lane to create GH release with description with 3 sections, with placeholder Changelog first, renaming what used to be called Changelog->Pull Requests (and thirdly Dependencies) …
=> Fastlane and README improvments

.github/workflows/cd.yml
separate concurrency groups from `CD-workflow_dispatch` and `CD_push` to:
- CD-workflow_dispatch-pre-alpha
- CD-workflow_dispatch-alpha
- CD-workflow_dispatch-beta
- CD-workflow_dispatch-release
- CD-push
Only group `CD-workflow_dispatch-release` will cancel any build in progress others will queue.
=> ci/cd - update cancellation rules

RadixWallet/Features/ImportMnemonic/ImportMnemonic+View.swift, RadixWallet/Features/ImportMnemonic/ImportMnemonic.swift, RadixWallet/Features/SettingsFeature/ImportFromOlympiaLegacyWallet/Coordinator/ImportOlympiaWalletCoordinator+View.swift, RadixWallet/Features/SettingsFeature/ImportFromOlympiaLegacyWallet/Coordinator/ImportOlympiaWalletCoordinator.swift
Jira ticket: [ABW-2456](https://radixdlt.atlassian.net/browse/ABW-2456)
Show a warning after entering the seed phrase when importing Olympia accounts.
- Import Olympia software accounts
- Enter seed phrase
-> Should show warning
- Try all other ways to see the seed phrase screen 
-> Should NOT show warning
[ABW-2456]: https://radixdlt.atlassian.net/browse/ABW-2456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2456] Seed Phrase Warning When Importing Olympia Accounts

RadixWallet/Clients/SecureStorageClient/SecureStorageClient+Live.swift, RadixWallet/Features/DerivePublicKeys/DerivePublicKeys.swift, RadixWallet/Features/SettingsFeature/DisplayMnemonics/Children/DisplayMnemonic.swift, RadixWallet/Features/Signing/Children/Factors/SignWithFactorSourcesOfKindReducerProtocol.swift
Jira ticket: https://radixdlt.atlassian.net/browse/ABW-2511
Moved the check in a single place, where we do know for sure that the mnemonic is missing. Was initially reticent to put the alert in secureStorageClient, to not be too upfront with displaying the alert, but it works well in current setup. We should move this potentially closer to UI, when we will have a dedicated sheet for reading the mnemonic from the Keychain.
=> Properly check for the missing mnemonic

RadixWallet/Clients/DeviceFactorSourceClient/DeviceFactorSourceClient+Live.swift, RadixWallet/Clients/SecureStorageClient/SecureStorageClient+Interface.swift, RadixWallet/Clients/SecureStorageClient/SecureStorageClient+Live.swift, RadixWallet/Clients/SecureStorageClient/SecureStorageClient+Test.swift
We do a background check of the accounts in the splash screen, if the mnemonic is missing we could show the alert with missing mnemonic, but the context is not clear to user. For now, disable showing the alert in splash screen, will enable again when we do have an explicit screen that informs the user what operation is happening.
=> Quick fix - don't show missing mnemonic at startup

RadixWallet/Core/Resources/Generated/L10n.generated.swift, RadixWallet/Features/TransactionReviewFeature/CustomizeFees/CustomizeFees+View.swift
Use "No account selected" string
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/a099d901-a5db-4726-8a5d-3a2a5a5dede8
=> Make use of proper strings for Customize Fees

RadixWallet/Clients/DeviceFactorSourceClient/DeviceFactorSourceClient+Live.swift, RadixWallet/Core/DesignSystem/Components/WarningView.swift, RadixWallet/Core/FeaturePrelude/UserDefaultsClient+AccountRecovery.swift, RadixWallet/Core/SharedModels/Entities/EntitiesControlledByFactorSource.swift, RadixWallet/Features/DisplayEntitiesControlledByMnemonic/DisplayEntitiesControlledByMnemonic+Reducer.swift, RadixWallet/Features/DisplayEntitiesControlledByMnemonic/DisplayEntitiesControlledByMnemonic+View.swift, RadixWallet/Features/ImportMnemonic/ImportMnemonic.swift, RadixWallet/Features/ProfileBackupsFeature/ProfileBackupSettings/ProfileBackupSettings+Reducer.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ImportMnemonicControllingAccounts.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ImportMnemonicsFlowCoordinator.swift, RadixWallet/Features/SettingsFeature/DisplayMnemonics/Children/DisplayMnemonic.swift, RadixWallet/Features/SettingsFeature/DisplayMnemonics/Coordinator/DisplayMnemonics+View.swift, RadixWallet/Features/SettingsFeature/DisplayMnemonics/Coordinator/DisplayMnemonics.swift, RadixWallet/Features/SettingsFeature/ImportFromOlympiaLegacyWallet/Coordinator/ImportOlympiaWalletCoordinator.swift
This PR contains a fix for [ABW-2207](https://radixdlt.atlassian.net/browse/ABW-2207)
This PR improves UX in `Seed Phrases` screen in settings, by doing two new things:
* Prompting user to backup not yet backed mnemonics
* Prompting user to RECOVER a missing mnemonic, rather than incorrectly say they can display it - which leads to bug https://rdxworks.slack.com/archives/C03QFAWBRNX/p1698151009996849
https://github.com/radixdlt/babylon-wallet-ios/assets/116169792/a349351d-670e-4b4f-a2ff-ae3c4f9c7297
https://github.com/radixdlt/babylon-wallet-ios/assets/116169792/c868094c-cca1-49af-9d82-df11d18563ef
[ABW-2207]: https://radixdlt.atlassian.net/browse/ABW-2207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2207] Seed Phrase prompts - recover seed phrase if missing.

RadixWallet/Core/FeaturePrelude/AddressView/AddressFormat.swift, RadixWallet/Core/FeaturePrelude/AddressView/AddressView.swift, RadixWallet/Features/AccountPreferencesFeature/AccountPreferences+Reducer.swift, RadixWallet/Features/AccountPreferencesFeature/AccountPreferences+View.swift, RadixWallet/Features/AccountPreferencesFeature/Children/DevAccountPreferences+Reducer.swift, RadixWallet/Features/AccountPreferencesFeature/Children/DevAccountPreferences+View.swift
Jira ticket: [ABW-2415](https://radixdlt.atlassian.net/browse/ABW-2415)
We want to show the full account address, and the button to show the QR code, right in Account Preferences, as seen in [Figma](https://www.figma.com/file/6MaKVYek0m9GKkd1xujB8P/Babylon-Wallet?type=design&node-id=11004-38632&mode=design&t=m2KXOLS2rFZteKS7-0).
The QR code button is also removed from Dev preferences.
- Verify that the full address and the QR code button show up where they should, and that they work as expected
- Also verify that other address views look and behave as before
[ABW-2415]: https://radixdlt.atlassian.net/browse/ABW-2415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2415] Additions to Account Preferences

RadixWallet/Features/AssetsFeature/Components/HelperViews/AssetBehaviorsView.swift
Jira ticket: [ABW-2552](https://radixdlt.atlassian.net/browse/ABW-2552)
Don't show the information/metadata behaviour for XRD
This will eventually be handled on the "backend"
- Open XRD resource details and make sure that the metadata behaviour is not shown.
- If possible, check that the same behaviour is still there for some non-XRD resource
Before/after
[ABW-2552]: https://radixdlt.atlassian.net/browse/ABW-2552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2552] Hide XRD Metadata Behaviour

RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Row/NonFungbileAssetRow+Reducer.swift
Fix the issue when next page of the nfts will not be shown if there is 1 page + some additional nfts.
Original user report -> https://discord.com/channels/417762285172555786/870020556626477056/1169703332147904652
=> Fix NFT pagination issues

RadixWallet/Features/AccountDetailsFeature/Coordinator/AccountDetails+Reducer.swift, RadixWallet/Features/AccountDetailsFeature/Coordinator/AccountDetails+View.swift, RadixWallet/Features/AccountPreferencesFeature/AccountPreferences+Reducer.swift, RadixWallet/Features/HomeFeature/Coordinator/Home+View.swift, RadixWallet/Features/MainFeature/Main+View.swift
Jira ticket:
Alternative fix for hide account crash.
Tradeoffs:
- Can't edge swipe to go back from Account Details view
- Account Details title sometimes starts out black, before turning white
- Account Details back button and ellipsis are hidden when going back TO Account Details, until view is completely visible.
Note that the first three commits are not strictly necessary, but they do remove superfluous code that is related to the navigation stack.
Try to provoke a crash by hiding accounts
-> It should not crash
https://github.com/radixdlt/babylon-wallet-ios/assets/123396602/f92c7c15-ff80-4ff0-aedd-427c3e2100d2
=> Account hiding crash fix

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Jira ticket: [ABW-2538](https://radixdlt.atlassian.net/browse/ABW-2538)
Upgrade TCA fork to 1.3. Pairs with the newly re-forked version of the TCA library.
We fork exactly at 1.3, meaning we miss a handful of commits, but I presume the tagged versions are more solid.
General testing, the app should behave as before in every way.
[ABW-2538]: https://radixdlt.atlassian.net/browse/ABW-2538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2538] Upgrade TCA to 1.3

RadixWallet.xcodeproj/project.pbxproj, RadixWallet/Clients/FactorSourcesClient/FactorSourcesClient+Live.swift, RadixWallet/Clients/FaucetClient/FaucetClient+Interface.swift, RadixWallet/Clients/KeychainClient/KeychainClient+Interface.swift, RadixWallet/Clients/KeychainClient/KeychainClient+Live.swift, RadixWallet/Clients/KeychainClient/KeychainClient+Mocked.swift, RadixWallet/Clients/KeychainClient/KeychainHolder.swift, RadixWallet/Clients/SecureStorageClient/SecureStorageClient+Interface.swift, RadixWallet/Clients/SecureStorageClient/SecureStorageClient+Live.swift, RadixWallet/Clients/SecureStorageClient/SecureStorageClient+Test.swift, RadixWallet/Clients/UserDefaults+Dependency+Extension/UserDefaults+Dependency+Extension.swift, RadixWallet/Features/SettingsFeature/DebugSettings/Children/DebugKeychainContents/DebugKeychainContents+View.swift, RadixWallet/Features/SettingsFeature/DebugSettings/Children/DebugKeychainContents/DebugKeychainContents.swift, RadixWallet/Features/SettingsFeature/DebugSettings/Children/DebugUserDefaultsContents/DebugUserDefaultsContents+View.swift, RadixWallet/Features/SettingsFeature/DebugSettings/Coordinator/DebugSettingsCoordinator+Reducer.swift, RadixWallet/Features/SettingsFeature/DebugSettings/Coordinator/DebugSettingsCoordinator+View.swift, RadixWallet/Features/SettingsFeature/ImportFromOlympiaLegacyWallet/Coordinator/ImportOlympiaWalletCoordinator.swift, RadixWallet/Profile/Factor/FactorSourceID.swift, RadixWalletTests/Clients/FaucetClientTests/FaucetClientTests.swift, RadixWalletTests/Clients/ProfileStoreTests/ProfileStoreTests.swift, RadixWalletTests/Features/AccountDetailsFeatureTests/AccountDetailsFeatureTests.swift, RadixWalletTests/Features/AppFeatureTests/AppFeatureTests.swift, RadixWalletTests/Features/MainFeatureTests/MainFeatureTests.swift, RadixWalletTests/PreludeTests/UserDefaultsClientTests/UserDefaultsClientTests.swift, RadixWalletTests/TestExtensions/TestUtils.swift, fastlane/.env.ios
N.B. Target branch is not main
https://github.com/radixdlt/babylon-wallet-ios/assets/116169792/23105b20-e406-4b5a-a2bd-c38cbd942975
=> Debug Keychain View - delete mnemonics

RadixWallet/Clients/TransactionClient/Models/TransactionFailure.swift, RadixWallet/Clients/TransactionClient/TransactionClient+Live.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift
JIRA - https://radixdlt.atlassian.net/browse/ABW-2524
Display additional error message when a TX review failed due the receiving account Third-Party deposits config.
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/d6677d2c-d199-4617-a855-4ed39bd3befa
=> Specific message for third-party deposits failure

RadixWallet/Features/AssetTransferFeature/Components/TransferAccountList/ReceivingAccount/Asset/FungibleResourceAsset+Reducer.swift, RadixWallet/Features/AssetTransferFeature/Components/TransferAccountList/ReceivingAccount/Asset/FungibleResourceAsset+View.swift
JIRA - https://radixdlt.atlassian.net/browse/ABW-2497
Display contextual alerts when user tries to transfer the max amount of XRD. 
By setting the `defaultFee=1 XRD` the following logic is applied:
- When tapping Max button the remaining XRD amount is used as Max.
- If the remaining `XRD >= defaultFee`, we do display the alert allowing users to choose the amount.
- If the remaining `XRD < defaultFee`, we do display the alert informing the user that they will have to pay the fee from other account.
#Demo
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/ea855b02-29c7-4321-934d-961b9a21fb46
=> Max XRD transfer

RadixWallet/Clients/CacheClient/CacheClient+Interface.swift, RadixWallet/Clients/DappInteractionClient/DappInteractionClient+Interfce.swift, RadixWallet/Clients/DappInteractionClient/DappInteractionClient+Live.swift, RadixWallet/Clients/OnLedgerEntitiesClient/OnLedgerEntitiesClient+Interface.swift, RadixWallet/Clients/ROLAClient/ROLAClient+Live.swift, RadixWallet/Core/DesignSystem/Components/Thumbnails.swift, RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift, RadixWallet/Profile/AuthorizedDapp/AuthorizedDapp.swift
Jira ticket: [ABW-2558](https://radixdlt.atlassian.net/browse/ABW-2558)
Tries to fix the issue where some users can't connect to dApps anymore, by removing caching of dApp metadata for validation requests.
Also propagates the underlying error to the dApp response (and the UI if in dev mode), so that we can debug this issue if it persists.
Try to connect to dApps like Gable. This should work, and if it doesn't, please screenshot the error message!
[ABW-2558]: https://radixdlt.atlassian.net/browse/ABW-2558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2558] Investigate, potentially fix dApps issue

RadixWallet/Clients/ProfileStore/ProfileStore.swift, RadixWalletTests/Clients/ProfileStoreTests/ProfileStoreTests.swift, RadixWalletTests/ProfileTests/Utils/ProfileBuilder.swift, RadixWalletTests/TestExtensions/TestUtils.swift
Fixes an unlikely corner case, but possible. The Profile does not contain any accounts and
the BDFS mnemonic is missing => treat this scenario as if there is no Profile ->
let user start fresh. It is possible for users to end up in this corner case scenario
if the do this:
1. Start wallet without any Profile => a new Profile and BDFS is saved into keychain (and BDFS mnemonic)
2. Before they create the first account, they delete the passcode from their device and re-enabling it, this will delete the mnemonic from keychain, but not the Profile.
3. Start wallet again, and they are met with onboarding screen to create their first account into the empty Profile created in step 1. HOWEVER, they user is now stuck in a bad state. The account creation will try to use a missing mnemonic which …
=> [ABW-2575] WIP Fix cornercase bug where wallet ends up in bad state if user deletes iOS passcode before creating first account

RadixWallet/Features/DisplayEntitiesControlledByMnemonic/DisplayEntitiesControlledByMnemonic+View.swift, RadixWallet/Features/HomeFeature/Coordinator/Home.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ImportMnemonicsFlowCoordinator.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Coordinator/RestoreProfileFromBackupCoordinator.swift, RadixWallet/Features/SettingsFeature/DisplayMnemonics/Coordinator/DisplayMnemonics.swift, RadixWalletTests/TestExtensions/TestUtils.swift
Make it possible to create Main BDFS outside of onboarding.
https://github.com/radixdlt/babylon-wallet-ios/assets/116169792/5cf75b83-8859-4160-8ef0-33dbe3e0008f
=> Support creation of MAIN BDFS from outside of onboarding

RadixWallet/Features/AccountPreferencesFeature/AccountPreferences+View.swift, RadixWallet/Features/AssetTransferFeature/Components/TransferAccountList/ReceivingAccount/Asset/FungibleResourceAsset+Reducer.swift
Two quick small fixes:
- Hide Dev Preferences section for mainnet.
- Add cancel button in Max XRD alert.
- Don't show max XRD alert is remaining amount is zero
=> Small fixes

RadixWallet/Core/Resources/Generated/L10n.generated.swift, RadixWallet/Features/ProfileBackupsFeature/ProfileBackupSettings/ProfileBackupSettings+View.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ConfirmSkippingBDFS/ConfirmSkippingBDFS+View.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/SelectBackup/SelectBackup+View.swift
[Jira ABW-2598](https://radixdlt.atlassian.net/browse/ABW-2598)
=> Abw 2598 UI teaks main seed phrase required

RadixWallet/Core/FeaturePrelude/AddressView/AddressView.swift, RadixWallet/Features/DappInteractionFeature/Children/Completion/Completion+View.swift, RadixWallet/Features/DappInteractionFeature/Children/Completion/Completion.swift, RadixWallet/Features/DisplayEntitiesControlledByMnemonic/DisplayEntitiesControlledByMnemonic+View.swift, RadixWallet/Features/TransactionReviewFeature/SubmitTransaction/SubmitTransaction+View.swift
Jira ticket: ABW-2569
- Alignment of transaction id in Completion and In progress slide ups
- Color and font for the label "Transaction id" in the same screens
- Use the TCA dismiss dependency in the Completion slide up
- Appearance of "Hidden Accounts Only" box in Seed Phrases
paste link here
=> [ABW-2569] Success Screen Alignment and Various Small Fixes

RadixWallet/Features/DappsAndPersonas/DappDetails/DappDetails+View.swift
Jira ticket: ABW-2602
The navigation destinations from the dApp details screen got lost in a merge, making it impossible to forget a dApp or open details on NFTs/fungibles. This PR brings them back.
- Connect a dApp
- Open details on an NFT and a fungible
- Press the Forget dApp button
https://share.icloud.com/photos/0a8k_VgaK8OLHlrGoRMxmL8AA
=> [ABW-2602] Fix Dapp Details Navigation

.github/workflows/ci.yml, RadixWallet/Features/AssetsFeature/Components/PoolUnitsList/Components/PoolUnit/PoolUnit+View.swift, RadixWallet/Features/DappInteractionFeature/Children/Completion/Completion+View.swift
[Slack thread](https://rdxworks.slack.com/archives/C05V4202J90/p1700474625827809)
The user with account [account_rdx128ldshjmrge7j98ydag7qgsdk2t79qqlxpw5j2warzqnju7mg6x605](https://dashboard.radixdlt.com/account/account_rdx128ldshjmrge7j98ydag7qgsdk2t79qqlxpw5j2warzqnju7mg6x605/pool-units) experienced a crash when opening the pool unit view. This turned out to be because the total supply of Ociswap LP XRD/BCN was `0`, which caused a division-by-zero crash. This PR displays the text "Total supply is 0 - could not calculate redemption value", similar to how we already handle the case when the total supply property is missing.
=> Prevent PoolUnits crash

RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ConfirmSkippingBDFS/ConfirmSkippingBDFS+View.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ConfirmSkippingBDFS/ConfirmSkippingBDFS.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ImportMnemonicControllingAccounts+View.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ImportMnemonicControllingAccounts.swift, RadixWallet/Features/SplashFeature/Splash.swift
Change from real navigation title to a fake one in `ImportMnemonicControllingAccounts` so that `Main Seed Phrase Required` does not get truncated.
Fix appearance of skip button.
Use close button on bottom sheet shown when pressing skip.
=> fix title in ImportMnemonicControllingAccounts

RadixWallet/Clients/PersonasClient/PersonasClient+Interface.swift, RadixWallet/Features/HomeFeature/Coordinator/Home.swift, RadixWallet/Features/SettingsFeature/Settings+Reducer.swift, RadixWallet/Features/SettingsFeature/Settings+View.swift
Jira ticket: [ABW-2624](https://radixdlt.atlassian.net/browse/ABW-2624)
The Link Connector box in settings was not showing properly, which was caused by underlying issues with .task and the async sequences we have there. This was simplified and fixed.
[ABW-2624]: https://radixdlt.atlassian.net/browse/ABW-2624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2624] Fix Settings P2P link box

RadixWallet/Features/SettingsFeature/AccountSecurity/ManualAccountRecoveryScan/ManualAccountRecoveryCoordinator+Reducer.swift, RadixWallet/Features/SettingsFeature/AccountSecurity/ManualAccountRecoveryScan/ManualAccountRecoveryCoordinator+View.swift
Hide the Olympia section of manual account recovery in settings, when not on mainnet.
https://rdxworks.slack.com/archives/C031A0V1A1W/p1702031619345969
=> Only show Olympia recovery on Mainnet

RadixWallet/Features/SettingsFeature/AccountSecurity/AccountSecurity+Reducer.swift, RadixWallet/Features/SettingsFeature/AccountSecurity/AccountSecurity+View.swift, RadixWallet/Features/SettingsFeature/AppSettings/AppSettings+Reducer.swift, RadixWallet/Features/SettingsFeature/AppSettings/AppSettings+View.swift, RadixWallet/Features/SettingsFeature/Settings+Reducer.swift, RadixWallet/Features/TransactionReviewFeature/AccountDepositSettings/AccountDepositSettings+View.swift
Jira ticket: ABW-2493
Moves backup settings to the Account and Security Settings screen
=> [ABW-2493] Move Backup Settings to Security Settings

RadixWallet/Core/SharedModels/Entities/EntitiesControlledByFactorSource.swift, RadixWallet/Features/DisplayEntitiesControlledByMnemonic/DisplayEntitiesControlledByMnemonic+Reducer.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ImportMnemonicControllingAccounts.swift
(Android already does this) List a Factor Source in `App Settings -> Account Sec & Settings -> Seed Phrases` even if it does not control any account, i.e. for DFS call it `X` we with `CP_BAO` we show it as an ODFS and a BDFS, even it `X` controls 0 Babylon accounts and/or 0 Olympia accounts.
(Video too large for GH)
[Slack](https://rdxworks.slack.com/archives/C03QFAWBRNX/p1702378108609239)
However, when prompted to Import Mnemonics we show ONLY Babylon accounts if any, if no Babylon accounts and if Olympia accounts, we show them.
Where we left off from Demo 1, the state of the Profile, is that contains 3 factor sources, all with both set of crypto parameters (support both Olympia and Babylon) see screenshot, and then watch demo video.
We should only be asked for three mnemonics, and for …
=> Show Factor Source in Seed Phrases even if it controls 0 accounts

RadixWallet/Core/FeaturePrelude/AddressView/AddressView.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Details/NonFungibleTokenDetails+View.swift, RadixWallet/Features/AssetsFeature/Components/PoolUnitsList/Components/LSUResource/LSUStake+View.swift, RadixWallet/Features/AssetsFeature/Components/PoolUnitsList/Components/LSUResource/LSUStake.swift
Display the stake claim nft details
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/5895b7e6-cecb-43f0-9d04-5ac435bddf4c
=> Show Stake Claim NFT details

RadixWallet/Clients/FactorSourcesClient/FactorSourcesClient+Live.swift, RadixWallet/Features/AccountRecoveryScan/Children/AccountRecoveryScanInProgress/AccountRecoveryScanInProgress.swift, RadixWallet/Features/AccountRecoveryScan/Coordinator/AccountRecoveryScanCoordinator.swift
[Jira Ticket](https://radixdlt.atlassian.net/browse/ABW-2651)
We accidentally did not read the current network... now MARS works on non mainnet (current network). 
Another important fix: if GW responds with error, we dismiss the flow (as intended)
https://github.com/radixdlt/babylon-wallet-ios/assets/116169792/a1668248-324b-4748-b893-d34f6a8eaee3
=> [ABW-2651] Enable MARS for non-Mainnet (current network)

RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift
Simply show the network name, if available, instead of its id.
=> Show name of the network instead of its id

RadixWallet/Features/AccountAndPersonaHidingFeature/AccountAndPersonaHiding+Reducer.swift, RadixWallet/Features/AccountAndPersonaHidingFeature/AccountAndPersonaHiding+View.swift, RadixWallet/Features/AccountPreferencesFeature/Children/DevAccountPreferences+Reducer.swift, RadixWallet/Features/AccountPreferencesFeature/Children/DevAccountPreferences+View.swift, RadixWallet/Features/AccountRecoveryScan/Children/AccountRecoveryScanInProgress/AccountRecoveryScanInProgress+View.swift, RadixWallet/Features/AccountRecoveryScan/Children/AccountRecoveryScanInProgress/AccountRecoveryScanInProgress.swift, RadixWallet/Features/AccountRecoveryScan/Coordinator/AccountRecoveryScanCoordinator.swift, RadixWallet/Features/ImportMnemonic/ImportMnemonic+View.swift, RadixWallet/Features/OnboardingFeature/Children/Startup/OnboardingStartup+View.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ConfirmSkippingBDFS/ConfirmSkippingBDFS+View.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ConfirmSkippingBDFS/ConfirmSkippingBDFS.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ImportMnemonicControllingAccounts+View.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/RecoverWalletWithoutProfile/Coordinator/RecoverWalletWithoutProfileCoordinator+View.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/RecoverWalletWithoutProfile/Coordinator/RecoverWalletWithoutProfileCoordinator.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/SelectBackup/SelectBackup+Reducer.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/SelectBackup/SelectBackup+View.swift
Fixes a number of different issues, see below
Go through all the scenarios pictures. Also make sure to test the MARS and OARS flows and pay particular attention to all the back/close/continue buttons, when they are visible, enabled/disabled and that they lead to reasonable locations.
**Restore Wallet From Backup: title appearance + close button**
**Main Seed Phrase Required: padding + scrolling**
**No main seed phrase - ditto + simplify code**
**import mnemonics: button behaviour** 
**Entity hiding: simplify code + appearance:**
**Dev account preferences: top button:**
**Dev account preferences, transaction review: close button + upper padding**
**hide close button in Add Inactive Accounts:**
**Hide the close button in Scan Complete in MARS:**
Before:
=> Various Issues

RadixWallet/Features/ImportMnemonic/ImportMnemonic+View.swift, RadixWallet/Features/ImportMnemonic/ImportMnemonic.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ImportMnemonicControllingAccounts.swift, RadixWallet/Features/SettingsFeature/AccountSecurity/ManualAccountRecoveryScan/ManualAccountRecoverySeedPhrase+View.swift
Jira ticket: [ABS-2662](https://radixdlt.atlassian.net/browse/ABW-2662)
This fixes some issues with seed phrase entry. It also upgrades the debug buttons with a new power. If you press the small "M", it will only paste in the mnemonic, not press continue. That makes it possible to test "almost correct" mnemonics etc.
The second issue mentioned in the ticket is partly due to using the automatic debug entry, which is not a realistic scenario, it will not typically be possible to press Continue with an invalid mnemonic.
https://github.com/radixdlt/babylon-wallet-ios/assets/123396602/7f896e5c-1d50-40ea-9162-d6f7cd391cea
=> [ABS-2662] Enter Seed Phrase Problems

RadixWallet/Features/AccountRecoveryScan/Children/AccountRecoveryScanInProgress/AccountRecoveryScanInProgress.swift
Jira ticket: [ABW-2656](https://radixdlt.atlassian.net/browse/ABW-2656)
When dismissing the Deriving Accounts scan panel during MARS the user will be stuck on an empty screen.
Dismiss in MARS:
https://github.com/radixdlt/babylon-wallet-ios/assets/123396602/46d93bf8-91b9-48ab-b33b-0a3bee2f89e2
Dismiss in OARS:
https://github.com/radixdlt/babylon-wallet-ios/assets/123396602/9a8b1cce-d892-4c93-be64-630bb662c2e4
This also seems to fix [ABW-2658](https://radixdlt.atlassian.net/browse/ABW-2658), I have not been able to reproduce it.
https://github.com/radixdlt/babylon-wallet-ios/assets/123396602/f79d91cb-d949-4300-8729-9731ae17029e
[ABW-2656]: https://radixdlt.atlassian.net/browse/ABW-2656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ABW-2658]: …
=> [ABW-2656] Deriving Accounts Issues

RadixWallet.xcodeproj/project.pbxproj, RadixWallet/Core/Resources/Generated/L10n.generated.swift, RadixWallet/Core/Resources/Resources/en.lproj/Localizable.strings, RadixWallet/Features/AccountPreferencesFeature/Children/DevAccountPreferences+Reducer.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionFlow.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionModels.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift
Show in the Transaction Review header the name and thumbnail of the dApp that is proposing the transaction.
=> Show the information about the dApp proposing the transaction

RadixWallet/Features/HomeFeature/Children/AccountRow/Home+AccountRow+View.swift
Jira ticket: [ABW-2844](https://radixdlt.atlassian.net/browse/ABW-2844)
The account assets row can overflow if there are stakes present.
This PR takes `stakedValidators` into account, which should solve it.
Find or mock an account that has 6+ fungibles, a pool unit and/or NFT, and a staked validator. In the account list the view should adjust the number of fungibles it shows, so that all other icons fit. To be clear, this worked properly for all "other icons" except staked validators, but that should also work now.
[ABW-2844]: https://radixdlt.atlassian.net/browse/ABW-2844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2844] Take Staked Validators Into Account

RadixWallet/Clients/TransactionClient/Models/TransactionModels.swift, RadixWallet/Clients/TransactionClient/TransactionClient+Live.swift, RadixWallet/Core/SharedModels/P2P/Dapp/Models/Interaction/Transactions/SendTransactionRequest.swift, RadixWallet/Core/SharedModels/P2P/Dapp/Models/Interaction/WalletInteraction+PreviewValue.swift, RadixWallet/Features/AccountPreferencesFeature/Children/DevAccountPreferences+Reducer.swift, RadixWallet/Features/AccountPreferencesFeature/Children/ThirdPartyDeposits/ThirdPartyDeposits+Reducer.swift, RadixWallet/Features/AssetTransferFeature/AssetTransfer+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/StakeUnitList.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionFlow.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift, RadixWallet/RadixConnect/RadixConnect/RTC/RTCClients.swift, RadixWalletTests/Core/SharedModelsTests/DappModelsTests/DappModelsTests.swift, RadixWalletTests/Features/TransactionReviewFeatureTests/CustomizeFeePayerTests.swift
Main problem was that we were eagerly creating the TransactionManifest as part of the dApp request decoding, therefore if the manifest was invalid, the whole dApp request was invalid and we were not able to respond bacl.
This PR, moves up the TransactionManifest creation into TransactionClient. This allows identifying the invalid transaction manifest and respond back to dApp with proper error message.
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/dff5f657-4e76-4098-9cf4-68eb503e4e81
=> Handle malformed manifest request

RadixWallet.xcodeproj/project.pbxproj, RadixWallet/Clients/OnLedgerEntitiesClient/OnLedgerEntitiesClient+Interface.swift, RadixWallet/Core/DesignSystem/Components/PoolUnitView.swift, RadixWallet/Core/DesignSystem/Components/TransferPoolUnitView.swift, RadixWallet/Core/Resources/Generated/L10n.generated.swift, RadixWallet/EngineKit/Address.swift, RadixWallet/EngineKit/ReviewedTransaction.swift, RadixWallet/Features/AssetsFeature/AssetsView+View.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Details/NonFungibleTokenDetails+View.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/Components/LiquidStakeUnitView.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/Components/StakeClaimNFTsView.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/Components/ValidatorStakeView.swift, RadixWallet/Features/TransactionReviewFeature/TrackedPoolInteraction.swift, RadixWallet/Features/TransactionReviewFeature/TrackedValidatorInteraction.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview+Sections.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewAccount/TransactionReviewAccount+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewDapps/TransactionReviewDapps+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewDapps/TransactionReviewDapps.swift
Jira ticket: ABW-2256
Adds support for staking and unstaking manifests in transaction review
Stake/Unstake using https://dashboard.radixdlt.com/network-staking and make sure that the transaction review looks as in Zeplin.
https://github.com/radixdlt/babylon-wallet-ios/assets/123396602/d55ec2cd-c864-4436-8d84-5eda3b39d900
https://github.com/radixdlt/babylon-wallet-ios/assets/123396602/9e0cd6fc-f99a-4d50-bbfa-93fd09f4ac70
=> [ABW-2256] Transaction Review Staking and Unstaking

RadixWallet/Features/TransactionReviewFeature/TransactionReview+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift
Jira ticket: ABW-2720
Show warning alert for transactions that have to be displayed as raw
Send a non-conforming transaction, that should trigger the alert
=> [ABW-2720] Complex Transaction Warning

RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewGuarantees/MinimumPercentageStepper/MinimumPercentageStepper.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewGuarantees/TransactionReviewGuarantees+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewGuarantees/TransactionReviewGuarantees.swift
- Make transaction review support LSUs
- Make the guarantee view show the divisibility rounded number right away
- Stake
- Make sure that the "Customize guarantees" button is present and that it works
This also shows rounding (we pretend that the resource has a divisibility of 3):
https://github.com/radixdlt/babylon-wallet-ios/assets/123396602/d72d6f53-35e4-4034-8a62-7a17b048a97e
=> Guarantees for LSUs

RadixWallet/Core/Resources/Generated/L10n.generated.swift, RadixWallet/Core/Resources/Resources/en.lproj/Localizable.strings, RadixWallet/Core/SharedModels/HTTPURLSessionResponse/HTTPURLSessionResponse.swift
Identify and display the 429 bad HTTP response code.
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/13101e3e-2137-44e6-bb61-188856297702
=> Display rate limit error on 429 GW response.

RadixWallet/Features/TransactionReviewFeature/TransactionReview+Sections.swift
Aggregate the transfer amounts for the same resource for the same account.
The RET analysis might return multiple withdrawls/deposits for the same resource, instead of showing separate entries for each withdral/deposit, we aggregate the fungible amounts or the non fungible ids.
This aggregates only the guranteed amounts,  predicted amounts cannot be aggregated since each amount will have a specific instruction index attached.
This is only used curently for stake claim transactions, when the Dapp might sent a manifest which is interpreted by RET as having multiple distinct withdrawls/deposits for the same resource.
This should eventually be moved to RET, so it should return the aggregated amounts
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/9ff86e0a-53e9-4067-acec-75dd513 …
=> Stake claime transaction aggregate amounts

RadixWallet/Clients/RadixConnectClient/RadixConnectClient+Interface.swift, RadixWallet/Clients/RadixConnectClient/RadixConnectClient+Live.swift, RadixWallet/Clients/RadixConnectClient/RadixConnectClient+Test.swift, RadixWallet/Features/ProfileBackupsFeature/ProfileBackupSettings/ProfileBackupSettings+Reducer.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Coordinator/RestoreProfileFromBackupCoordinator.swift
Connect to the P2PLinks during the profile Restore from Backup flow.
- Don't remove the P2PLinks from the Profile when deleting the Wallet, so those are not lost when trying to Restore from Backup.
- When user starts the Restore from Backup flow, the Wallet pro-actively connects to the P2PLinks from the selected Profile. 
- While it was possible to connect to P2PLinks only when landing on home screen, connecting pro-actively in Restore from Backup flow, would make the experience of needing to use a Ledger device during the flow a lot better.
- If user leaves the Restore from Backup flow, RadixConnect will remove the established connections.
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/a4d52339-1fce-4195-b6a5-b9fee83f123f
=> Linked connector not restoring after iCloud restore

RadixWallet/Features/TransactionReviewFeature/CustomizeFees/CustomizeFees.swift
Jira ticket: [ABW-2913](https://radixdlt.atlassian.net/browse/ABW-2913)
Previously we used this logic, when changing fee payers:
1. Create a list of signers, based on the manifest + the new feePayer
2. Remove the previous feePayer unless it's also in the manifest
3. Force create a non-empty set of signers
The problem was that this was done even if the old feePayer that happened to be the same as the new.
I made the following changes:
1. I only replace the fee payer at all if it has changed, so the logic above would not get called in vain
2. The order inside the function was changed to first remove the old one, then add the new
3. We no longer force create the non empty set, instead we throw an error it (impossibly) is empty
As in the ticket
[ABW-2913]: …
=> [ABW-2913] Customize Fees Crash

RadixWallet/Core/DesignSystem/Components/Thumbnails.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/Components/ValidatorHeaderView.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview+View.swift
Proper default icon for validators without any icon
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/dd9ff549-e2d3-4c48-9fe8-c2db03f29a1b
=> Proper default icon for validators without any icon

RadixWallet/Features/TransactionReviewFeature/TransactionReview+Sections.swift
Manifests classified as `.general` should be considered:
- as `.transfer` if it has withdrawals or deposits
- non-conforming if it doesn't
=> Treat only "general" with transfers as "transfer"

RadixWallet/Core/DesignSystem/Components/PoolUnitView.swift, RadixWallet/Features/AssetsFeature/Components/PoolUnitsList/Components/PoolUnit+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewAccount/TransactionReviewAccount+View.swift
Jira ticket: [ABW-2905](https://radixdlt.atlassian.net/browse/ABW-2905)
This PR makes it so that guaranteed amounts for pool units are shown.
It also updates the guarantee amount view for fungible tokens to use the new design.
With this PR we will also start showing the amount of pool units that are owned, both in the portfolio and when selecting an asset for transfer. Do we want to suppress this?
Also, do we want to add the amount (including estimated/guaranteed amount) for LSUs?
Both of these changes are quite trivial.
[ABW-2905]: https://radixdlt.atlassian.net/browse/ABW-2905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2905] Show Guarantees for Pool Units

RadixWallet/Features/AccountAndPersonaHidingFeature/AccountAndPersonaHiding+Reducer.swift, RadixWalletTests/Features/AccountAndPersonaHidingTests/AccountAndPersonaHidingTests.swift
Jira ticket: https://radixdlt.atlassian.net/browse/ABW-3006
Now user is able to unhide the Accounts and Personas again.
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/afab2e76-779c-4306-a480-bace42d849a2
=> Fix Account&Persona unhide

RadixWallet/Clients/SubmitTransactionClient/SubmitTransactionClient+Live.swift, RadixWallet/Features/TransactionReviewFeature/SubmitTransaction/SubmitTransaction+View.swift, RadixWallet/Features/TransactionReviewFeature/SubmitTransaction/SubmitTransaction.swift
Identify and display the proper error message for assertion failed errors.
1. Execute tx with guarantees > 100%
2. Observe failure message
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/15e1b0e7-547b-469e-8b96-f9e43df70705
=> Assertion failed message for Guarantees

RadixWallet/Clients/AccountPortfoliosClient/AccountPortfoliosClient+Interface.swift, RadixWallet/Clients/AccountPortfoliosClient/AccountPortfoliosClient+Live.swift, RadixWallet/Clients/AccountPortfoliosClient/AccountPortfoliosClient+Mock.swift, RadixWallet/Clients/AccountPortfoliosClient/AccountPortfoliosClient+State.swift, RadixWallet/Clients/TokenPriceClient/TokenPriceClient+Live.swift, RadixWallet/Core/FeaturePrelude/Loadable.swift, RadixWallet/Features/AssetsFeature/AssetsView+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/FungibleAssetList/FungibleAssetList+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/HelperViews/ResourceBalance/ResourceBalanceView.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/NonFungibleAssetList+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/Components/ValidatorStakeView.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/StakeUnitList.swift, RadixWallet/Features/HomeFeature/Children/AccountRow/Home+AccountRow+Reducer.swift, RadixWallet/Features/HomeFeature/Children/AccountRow/Home+AccountRow+View.swift, RadixWallet/Features/HomeFeature/Coordinator/Home+View.swift, RadixWallet/Features/HomeFeature/Coordinator/Home.swift, RadixWallet/Features/HomeFeature/Models/AccountWithInfoHolder.swift
Reduce the slowness of loading the home screen.
After introducing fiatWorth on home screen, there are many more events which do trigger the updated of the state.
TCA seems to have issues when many actions are emitted in quick-ish succession, it has high impact on the main thread since all of the actions are resolved on the main thread.
There is still a small lag with this, potentially SharedState would help resolve this.
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/020def6d-3c3f-494d-9823-7e0761de24e5
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/96be6621-8ce7-4279-977d-50df1d1632b7
#CPU load before
=> Home Screen load laggines

RadixWallet/EngineKit/IsXRDResource.swift, RadixWallet/Features/AssetsFeature/AssetsView+Reducer.swift, RadixWallet/Features/AssetsFeature/AssetsView+View.swift, RadixWallet/Features/AssetsFeature/Components/DetailsContainerWithHeaderView.swift, RadixWallet/Features/AssetsFeature/Components/HelperViews/ResourceBalance/ResourceBalanceView+Helpers.swift, RadixWallet/Features/AssetsFeature/Components/HelperViews/ResourceBalance/ResourceBalanceView.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/Components/StakeSummaryView.swift
Final-final-v6 round of bug fixing...
Fix for AdHoc reported bugs:
- Showing Fiat values for release builds in Assets and details.
- Not being able to enter pool units amount
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/df1ae2d0-2d97-4872-8d91-04f33a9a7e8b
=> Fixes round 3

Aux/Config/Common.xcconfig, RadixWallet.xcodeproj/project.pbxproj, RadixWallet/Clients/AccountPortfoliosClient/AccountPortfoliosClient+Live.swift, RadixWallet/Clients/TokenPriceClient/TokenPriceClient+Live.swift, RadixWallet/Core/FeaturePrelude/AddressView/AddressFormat.swift, RadixWallet/EngineKit/TXID.swift, RadixWallet/Features/AssetsFeature/AssetsView+Reducer.swift, RadixWallet/Features/HomeFeature/Children/AccountRow/Home+AccountRow+View.swift, RadixWalletTests/Clients/TokenPriceCientTests/TokenPriceCientTests.swift
1.5.0 Hot fixes
- Properly truncate price before initialising the RETDecimal.
- Apply empty vaults when refreshing the portfolio for a given account.
- TXID truncation.
FLOOP worth:
Tokens with near zero value are still shown
TXID truncation
=> 1.5.0 Hot fixes

RadixWallet/Core/FeaturePrelude/AddressView/AddressView.swift, RadixWallet/Features/AssetsFeature/Components/HelperViews/AssetResourceDetails.swift, RadixWallet/Features/AssetsFeature/Components/HelperViews/GeneralHelperViews.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Details/NonFungibleTokenDetails+View.swift, RadixWallet/Features/DappsAndPersonas/DappDetails/DappDetails+View.swift
Jira ticket: [ABW-3022](https://radixdlt.atlassian.net/browse/ABW-3022)
Changed the copy address icon color wherever it was incorrect.
[ABW-3022]: https://radixdlt.atlassian.net/browse/ABW-3022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3022] Copy address icon colour

RadixWallet/Features/AccountPreferencesFeature/AccountPreferences+Reducer.swift, RadixWallet/Features/AccountPreferencesFeature/AccountPreferences+View.swift, RadixWallet/Features/AccountPreferencesFeature/Children/DevAccountPreferences+Reducer.swift, RadixWallet/Features/AccountPreferencesFeature/Children/DevAccountPreferences+View.swift
Jira ticket: [ABW-3026](https://radixdlt.atlassian.net/browse/ABW-3026)
Moved “Get XRD Tokens“ button from Development Preferences to AccountSettings screen
https://github.com/radixdlt/babylon-wallet-ios/assets/163979791/03b95afa-703c-4212-8835-903a173bebd2
[ABW-3026]: https://radixdlt.atlassian.net/browse/ABW-3026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3026] Account settings XRD faucet placement

Aux/PrivacyInfo.xcprivacy, RadixWallet.xcodeproj/project.pbxproj
We required to implement the [Describing use of required reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)
From the documentation and our codebase, the only thing that requires to declare the reason is UserDefaults.
Even though the Apple email suggested that we do also need to provide the description for the following:
- [File timestamp APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393)
- [System boot time APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394)
- [Disk space APIs](https://developer.apple.com/documentation/bundleresources/privacy_manif …
=> Describing use of required reason API

RadixWallet/Features/TransactionReviewFeature/TransactionReview+View.swift
Jira ticket: [ABW-2908](https://radixdlt.atlassian.net/browse/ABW-2908)
Show the title in the navigation bar in Transaction Review, when scrolling away the other title.
We could do the same thing in other places too, like the home screen, it's fairly painless.
- Go to transaction view and scroll down far enough for the main title to disappear.
https://github.com/radixdlt/babylon-wallet-ios/assets/123396602/0bad2d48-0b58-46c7-8386-ddc78e864e75
[ABW-2908]: https://radixdlt.atlassian.net/browse/ABW-2908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [AVW-2908] Transaction Review Header

Aux/PrivacyInfo.xcprivacy
Addition of description of API usages. The app does not seem to make use of these, and I couldn't identify the libraries which could make use of these. I have added the most appropriate reasons for our app.
Potentially [WebRTC lib](https://github.com/stasel/WebRTC/issues/92) could make use of some APIs.
=> Add additional descriptions for the used APIs

PreviewApps/ManageSecurityStructurePreview/ManageSecurityStructurePreviewApp.swift, PreviewApps/SecurityStructureConfigurationListPreview/SecurityStructureConfigurationListPreviewApp.swift, RadixWallet.xcodeproj/project.pbxproj, RadixWallet/Clients/TransactionHistoryClient/TransactionHistoryClient+Interface.swift, RadixWallet/Clients/TransactionHistoryClient/TransactionHistoryClient+Live.swift, RadixWallet/Core/FeaturePrelude/Extensions/AnyRange.swift, RadixWallet/Core/SharedModels/Assets/OnLedgerEntity.swift, RadixWallet/Cryptography/Mnemonic/BIP39/BIP39+WordList.swift, RadixWallet/Features/DappInteractionFeature/Children/AccountPermissionChooseAccounts/AccountPermissionChooseAccounts+Reducer.swift, RadixWallet/Features/ManageSecurityStructure/Children/FactorSourcesOfKindList/FactorSourcesOfKindList.swift, RadixWallet/Features/TransactionHistory/TransactionHistory+Reducer.swift
Slack discussion: [thread](https://rdxworks.slack.com/archives/C05V4202J90/p1712242660583689)
Some users have experienced an HTTP error, that may be due to them having their clock going a little fast. When we make the requests in transaction history, the Gateway will complain if the upper bound date is more than a few seconds into the future.
This PR removes the upper bound when it would have otherwise been *now*. 
I tested setting the clock forward and on main that does cause the 400 error, and it is indeed fixed by this PR.
It also improves the handling when there are no transactions at all.
=> Fix 400 error in transaction history

RadixWallet/Clients/TransactionClient/Models/TransactionFee.swift, RadixWallet/Features/SettingsFeature/AccountSecurity/DefaultDepositGuarantees/DefaultDepositGuarantees+Reducer.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewGuarantees/TransactionReviewGuarantees.swift, RadixWallet/Profile/AppPreferences/Transaction/AppPreferences+Transaction.swift
This PR fixes the initialization of `Decimal192` from literal `Float`, which isn't possible on RELEASE.
Reason why CD is [failing](https://github.com/radixdlt/babylon-wallet-ios/commit/1f6c403665bd94f8f120e5e8808b2559111d0635/checks).
=> Fix Decimal192 initialization on release

RadixWallet/Clients/P2PLinksClient/P2PLinksClient+Interface.swift, RadixWallet/Clients/P2PLinksClient/P2PLinksClient+Live.swift, RadixWallet/Clients/P2PLinksClient/P2PLinksClient+Test.swift, RadixWallet/Clients/SecureStorageClient/SecureStorageClient+Interface.swift, RadixWallet/Clients/SecureStorageClient/SecureStorageClient+Live.swift, RadixWallet/Clients/SecureStorageClient/SecureStorageClient+Test.swift, RadixWallet/Core/Resources/Generated/L10n.generated.swift, RadixWallet/Core/Resources/Resources/en.lproj/Localizable.strings, RadixWallet/Features/NewConnectionFeature/Coordinator/NewConnection+Reducer.swift, RadixWallet/RadixConnect/RadixConnect/RTC/PeerConnection/PeerConnectionNegotiator.swift
Updates for PR [#1089](https://github.com/radixdlt/babylon-wallet-ios/pull/1089)
What was updated:
- After 1.6.0 is out, we will for sure encounter cases when users scan the old QR code, we may want to identify this and tell them that they are using old CE
- Updated the Wallet to have only one public key for all CE links, so CE can identify the Wallet as being the same client in the same way the Wallet sees the CE being the same client
=> CAP-36 New Linking Flow Updates

RadixWallet/Features/DappInteractionFeature/Children/Login/Coordinator/Login+View.swift
This PR solves a crash on debug builds reproduced if user tapped on `Create New Persona` too soon.
The crash has been identified through Xcode organizer, showing the issue described.
It has happened when using a very large profile with lots of accounts. I haven't been able to reproduce this issue (even with a similar profile) but the added solution should have no harm.
=> Disable Create new persona button before checking primacy

RadixWallet/Clients/P2PLinksClient/P2PLinksClient+Live.swift
Fix for those devices that have created P2P links from `pre-alpha 1.6.0 (3)` build.
Solution is to ignore `loadP2PLinks` decoding error when updating P2P links.
=> Fix P2P links loading

RadixWallet/Features/AccountRecoveryScan/Coordinator/AccountRecoveryScanCoordinator.swift
Bug reported by Umair in [Slack](https://rdxworks.slack.com/archives/C03QFAWBRNX/p1715600665660489)
This solves a bug where user would be locked (and forced to kill the app) when performing a Manual Account Recovery Scan with the seed phrase missing.
| - | - |
| https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/61a1ee87-e6c5-474e-9d98-9260866f80eb |  https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/2ad0b471-4668-4c31-b268-66fb9334bf16 |
The ideal behavior would be the sheet being closed when the `Ok` button is tapped on the alert. However, this would include a huge refactor since such alert is presented from the `SecureStorageClient` (using the `OverlayWindowClient`) and not from the View involved.
=> [BUG FIX] User locked in MARS failing flow

RadixWallet/Clients/RadixConnectClient/RadixConnectClient+Live.swift
Fixes the scenarios when `sendAccountListMessage` throws an error and stops the execution of the loop.
=> [CAP-36] Accounts sharing fix

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWalletTests/Clients/TransactionClientTests/TransactionClientTests.swift
Bump Sargon to version containing Bottlenose compatible RET / Scrypto
=> bump sargon to 0.7.18 (with RET / Scrypto bump)

RadixWallet/Features/SecurityCenterFeature/SecurityCenter+Reducer.swift, RadixWallet/Features/SecurityCenterFeature/SecurityCenter+View.swift
Jira ticket: [ABW-3333](https://radixdlt.atlassian.net/browse/ABW-3333)
This PR updates the action performed when tapping on each problem on `Security Center` view, following what's defined on [Confluence](https://radixdlt.atlassian.net/wiki/spaces/AT/pages/3392569357/Security-related+Problem+States+in+the+Wallet). 
The issue was just about `.problem9`, but I've included changes for `.problem3` as well. The remaining ones (`.problem5`, `.problem6` & `.problem7`) keep the existing behavior which is navigate to `Configuration Backup` view.
https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/fedfb4e6-18c4-49aa-b514-b53ca0c279b8
[ABW-3333]: https://radixdlt.atlassian.net/browse/ABW-3333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3333] Update action handling on Security Center

RadixWallet/Clients/AccountPortfoliosClient/AccountPortfoliosClient+Live.swift, RadixWallet/Clients/AccountPortfoliosClient/AccountPortfoliosClient+State.swift
Jira ticket: https://radixdlt.atlassian.net/browse/ABW-3336
Previously the Wallet considered that there is no token prices if the retrieval of these failed. With this PR the Wallet will show error state when the Wallet fails to fetch token prices.
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/7aca69f1-4d17-4f7d-b89c-9fd7ab14e835
=> Show fiat worth error state when price retrieval fails.

RadixWallet/Features/HomeFeature/Coordinator/Home.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ImportMnemonicsFlowCoordinator.swift
Jira ticket: [ABW-3349](https://radixdlt.atlassian.net/browse/ABW-3349)
Fixes the issue when the P2P links migration message didn't display after importing a profile from a local file.
Removed the delay added in `ImportMnemonicsFlowCoordinator` and added a `delayedMediumEffect` in `Home` to ensure all possible flows are covered.
[ABW-3349]: https://radixdlt.atlassian.net/browse/ABW-3349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CAP-36] Migration messages presentation fix

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Features/ProfileBackupsFeature/Shared/ExportableProfileFile.swift, RadixWallet/WalletApp.swift
This contains the 10x speedup to JSON Decoding and analysis of Profile
Contents and encryption/decryption, part of https://github.com/radixdlt/sargon/pull/144
>[!NOTE]
> Deprecations: I've deprecated the `Data` based API's or Profile in Swift Sargon since they are just convenience methods/functions which wrap `String.init:data:encoding)` and `String.data:encoding` utf8 roundtrips. So whenever we CAN we SHOULD use JSON `String` based API's directly, for maximum performance (i.e. when we add Persona avatars to Profile and it is several megabytes we might save some milliseconds avoiding unnessary `utf8` conversions).
> [!TIP]
> Enable Rust logging by default - it is **VERY verbose** you might wanna comment it out from WalletApp.swift
=> bump Sargon to 1.0.1

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Bump [Sargon to 1.0.2 which contains bug fix](https://github.com/radixdlt/sargon/pull/147), that fixes [this crash that Umair managed to cause using a non-sensical Transaction Manifest](https://rdxworks.slack.com/archives/C03QFAWBRNX/p1716550883466509)
=> bump Sargon to 1.0.2

RadixWallet/Clients/AccountPortfoliosClient/AccountPortfoliosClient+State.swift
Jira ticket: [ABW-3350](https://radixdlt.atlassian.net/browse/ABW-3350)
Fixes the issue causing account details to be stuck in infinite loading.
When a single portfolio was updated, `setOrUpdateAccountPortfolios` deleted all others values from `portfoliosSubject`.
[ABW-3350]: https://radixdlt.atlassian.net/browse/ABW-3350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3350] Fix account details not loading resources

RadixWallet/Clients/DeviceFactorSourceClient/DeviceFactorSourceClient+Interface.swift, RadixWallet/Clients/DeviceFactorSourceClient/DeviceFactorSourceClient+Live.swift, RadixWallet/Clients/DeviceFactorSourceClient/DeviceFactorSourceClient+Test.swift, RadixWallet/Clients/SecurityCenterClient/SecurityCenterClient+Interface.swift, RadixWallet/Clients/SecurityCenterClient/SecurityCenterClient+Live.swift, RadixWallet/Features/DisplayEntitiesControlledByMnemonic/DisplayEntitiesControlledByMnemonic+Reducer.swift, RadixWallet/Features/DisplayEntitiesControlledByMnemonic/DisplayEntitiesControlledByMnemonic+View.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ImportMnemonicControllingAccounts.swift, RadixWallet/Features/SettingsFeature/DisplayMnemonics/Coordinator/DisplayMnemonics.swift, RadixWallet/Features/SettingsFeature/Troubleshooting/ManualAccountRecoveryScan/ManualAccountRecoverySeedPhrase+View.swift
- Uses `SecurityCeneterClient` to determine problems inside `DisplayMnemonics`
- Update UI to look as Aftab requested
- Consider hidden accounts for problems.
| - | - |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-05-28 at 16 15 51](https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/e230390c-18c3-45bc-aefa-58ac5a1c9bb5) | ![problem3 after](https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/cdbc8d6e-3318-4e17-a430-b99ca2408cf9) |
| ![problem9 before](https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/c972a5c9-4b29-4114-b5da-872da490ce6a) | ![problem9 after](https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/46412ef4-442a-4a50-bc1d-e658b1139f89) |
=> Update Seed Phrases to use Security Client

RadixWallet.xcodeproj/project.pbxproj, RadixWallet/Clients/CloudBackupClient/CloudBackupClient+Live.swift, RadixWallet/RadixWalletBeta.entitlements
The old record type we used has gotten polluted with incorrect field names, so this PR introduces a new type, `ProfileV2`.
=> Change type for Profile record on CloudKit

RadixWallet/Core/SharedModels/Entities/EntitiesControlledByFactorSource.swift, RadixWallet/Features/DisplayEntitiesControlledByMnemonic/DisplayEntitiesControlledByMnemonic+Reducer.swift, RadixWallet/Features/DisplayEntitiesControlledByMnemonic/DisplayEntitiesControlledByMnemonic+View.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ImportMnemonicControllingAccounts.swift, RadixWallet/Features/SettingsFeature/DisplayMnemonics/Coordinator/DisplayMnemonics.swift, RadixWallet/Features/SettingsFeature/Settings+Reducer.swift, RadixWallet/Features/SettingsFeature/Troubleshooting/ManualAccountRecoveryScan/ManualAccountRecoverySeedPhrase+View.swift
Jira ticket: [ABW-3407](https://radixdlt.atlassian.net/browse/ABW-3407)
On the `Seed Phrases` view, each row will now indicate if it has any (visible) personas connected to it. Also, it will prompt the user to import/back up a seed phrase if it doesn't have any connected accounts but has personas 
| - | - |
| ![b1](https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/47385798-40b9-4140-ab9e-fe7570cf88fa) | ![a1](https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/7fa2b8a0-4884-4b72-97ca-2e9809416a10) |
| ![b2](https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/4750a35c-7d98-40dc-a281-23f05ed596fe) | ![a2](https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/f4a209d3-c6b4-4510-8cb9-86ab493acb81) | …
=> [ABW-3407] Indicate Personas connected to a Mnemonic

RadixWallet/Clients/SecurityCenterClient/SecurityCenterClient+Live.swift
To reproduce this bug, just follow these steps:
- Reset Wallet
- Create new Account
- Hide such account
- Open Settings 
| -- | -- |
| ![IMG_0046](https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/ed3b048e-ca0e-4179-9c15-ba2a0afb5471) | ![IMG_0045](https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/beb1ca23-63af-4920-aa6f-63cdd6724fe1) |
=> Fix bug where Security Problems where missing for hidden entities

RadixWallet/Features/DappsAndPersonas/Personas/Child/List/PersonaList+Reducer.swift
Improvement to https://github.com/radixdlt/babylon-wallet-ios/pull/1161/commits/fe183f962255a80cde072565661c5eae897d1749
=> Small improvement to Personas loading

RadixWallet/Clients/CloudBackupClient/CloudBackupClient+Live.swift, RadixWallet/Clients/FactorSourcesClient/FactorSourcesClient+Live.swift, RadixWallet/Clients/TransactionClient/Models/TransactionFailure.swift, RadixWallet/Clients/UserDefaults+Dependency+Extension/UserDefaults+Dependency+Extension.swift, RadixWallet/Core/DesignSystem/Components/Thumbnails.swift, RadixWallet/Core/SharedModels/P2P/Application/IncomingMessage/P2P+RTCIncomingMessage.swift, RadixWallet/Core/SharedModels/P2P/ConnectorExtension/P2P+ConnectorExtension+Response.swift, RadixWallet/Features/AccountPreferencesFeature/Children/DevAccountPreferences+Reducer.swift, RadixWallet/Features/AccountRecoveryScan/Coordinator/AccountRecoveryScanCoordinator.swift, RadixWallet/Features/AppFeature/App+Reducer.swift, RadixWallet/Features/AssetTransferFeature/AssetTransfer+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Details/NonFungibleTokenDetails+View.swift, RadixWallet/Features/CreateAccount/Coordinator/CreateAccountCoordinator+Models.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionFlow.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionModels.swift, RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift, RadixWallet/Features/DappsAndPersonas/AuthorizedDApps/AuthorizedDApps.swift, RadixWallet/Features/HomeFeature/Coordinator/Home.swift, RadixWallet/Features/ImportMnemonic/ImportWord/ImportMnemonicWord.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/ImportSeedPhrasesFlow/ImportMnemonicControllingAccounts.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/RecoverWalletWithoutProfile/Coordinator/RecoverWalletWithoutProfileCoordinator+View.swift, RadixWallet/Features/ProfileBackupsFeature/Shared/EncryptOrDecryptProfile+Reducer.swift, RadixWallet/Features/SettingsFeature/DebugSettings/Children/DebugUserDefaultsContents/DebugUserDefaultsContents.swift, RadixWallet/Features/SettingsFeature/DisplayMnemonics/Coordinator/DisplayMnemonics.swift, RadixWallet/Features/Signing/Coordinator/Signing.swift, RadixWallet/Features/TransactionReviewFeature/SubmitTransaction/SubmitTransaction.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview+Sections.swift, RadixWallet/RadixConnect/RadixConnect/RTC/SignalingClient/IncomingMessage/IncomingMessage+Decoding.swift
Instead of only updating the locally stored log of old backups when the user has backups turned on and we discover that no backup is present, this PR will make it so that we always update the log. This ensures that we don't show the `Out-of-date backup still present on iCloud` warning if the user manually deletes iCloud content from settings.
- Turn of Automatic backups
- Note that `Out-of-date backup still present on iCloud` is visible
- Manually delete iCloud contents from settings
- Note that the warning goes away
The scenario from How to test:
https://github.com/radixdlt/babylon-wallet-ios/assets/123396602/24f82413-01ef-4c65-9b9a-8fc66618fc2e
What happens if you delete the backup from within the app
https://github.com/radixdlt/babylon-wallet-ios/assets/123396602/84417444-655f-46e3-82bf …
=> Retroactively Update Backup Log

RadixWallet/Features/NewConnectionFeature/Coordinator/NewConnection+Reducer.swift
Fixes the error message that appears when scanning an old QR code.
=> Fix old QR code error message

RadixWallet/Clients/TransactionClient/TransactionClient+Live.swift, RadixWallet/Features/TransactionReviewFeature/SelectFeePayer/SelectFeePayer+View.swift
Jira ticket: [ABW-3432](https://radixdlt.atlassian.net/browse/ABW-3432)
- When selecting a fee payer account, show them in the same order as they are shown on Home
- Scroll to the preselected account so that it always shows up when opening the view.
| - | - |
| <video src=https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/e620f010-92a2-45c6-ae19-2abd37553657> | <video src=https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/1e96d6e1-59cb-4e16-a9c4-9ff44160a8bc> |
[ABW-3432]: https://radixdlt.atlassian.net/browse/ABW-3432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3432] Sort Fee Payer accounts as in Home

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift
Jira ticket: [ABW-3433](https://radixdlt.atlassian.net/browse/ABW-3433)
- Fixes the crash (by using a [new version](https://github.com/radixdlt/sargon/pull/170) of Sargon)
- Propagates the errors that come from Rust panics in the method `modify_manifest_add_guarantees`
Currently this would show an error along the lines of this (if forcing an index out of bounds panic), but we could wrap this in a generic error to hide the message, or leave as is, until the PR that lets users send the error to support:
[ABW-3433]: https://radixdlt.atlassian.net/browse/ABW-3433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3433] Fix Manifest Crash

RadixWallet.xcodeproj/project.pbxproj, RadixWallet/Clients/SecureStorageClient/SecureStorageClient+Live.swift, RadixWallet/Prelude/Throwable.swift
Jira ticket: [ABW-3456](https://radixdlt.atlassian.net/browse/ABW-3456)
This PR fixes the issue that occurs when we try to decode an invalid profile header. The solution is to filter out the invalid ones.
[ABW-3456]: https://radixdlt.atlassian.net/browse/ABW-3456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3456] Fix the decoding issue for `Profile.Header`

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/ContactSupportClient/ContactSupportClient+Live.swift, RadixWallet/Clients/ContactSupportClient/ContactSupportClient.swift, RadixWallet/Clients/OverlayWindowClient/OverlayWindowClient+Interface.swift, RadixWallet/Clients/OverlayWindowClient/OverlayWindowClient+Live.swift, RadixWallet/Core/Resources/Generated/L10n.generated.swift, RadixWallet/Features/AppFeature/Overlay/Overlay+Reducer.swift, RadixWallet/Features/SettingsFeature/Troubleshooting/Troubleshooting.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift
Jira ticket: [ABW-3454](https://radixdlt.atlassian.net/browse/ABW-3454)
Relates to [#168](https://github.com/radixdlt/sargon/pull/168)
- Display an abstracted message for Sargon errors with the option to email support and include more debugging info
- For debug mode, show an error code and the detailed error message from Sargon instead of the abstracted message
If you want to simulate this error from Sargon, you can scan this invalid QR code:
| Release example | Debug example |
| - | - |
| ![IMG_0014](https://github.com/radixdlt/babylon-wallet-ios/assets/163979791/82dfbe75-f073-4bc6-ab39-2f3bd9e3f3de) |  ![IMG_0013](https://github.com/radixdlt/babylon-wallet-ios/assets/163979791/6a4724c9-c346-4dd0-9dd7-974ebac1b68f) |
| Email body |
| - |
| …
=> Display an abstracted message for Sargon errors

RadixWallet.xcodeproj/project.pbxproj
Pin every dependency to the version that it was currently used (so there is no unexpected behavior change). 
The only one that isn't pinned to an exact version is [swift-either](https://github.com/pointfreeco/swift-either) since it doesn't have any version released. We may want to implement it ourselves since its GH page says it isn't production ready.
=> Pin all dependencies to exact version currently used

RadixWallet/Clients/CloudBackupClient/CloudBackupClient+Interface.swift, RadixWallet/Clients/CloudBackupClient/CloudBackupClient+Live.swift, RadixWallet/Clients/CloudBackupClient/CloudBackupClient+Test.swift, RadixWallet/Clients/TransportProfileClient/TransportProfileClient+Live.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/SelectBackup/SelectBackup+Reducer.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/SelectBackup/SelectBackup+View.swift, RadixWallet/Features/SecurityCenterFeature/ConfigurationBackup+Reducer.swift
Pursuant to [this discussion](https://rdxworks.slack.com/archives/C03QFAWBRNX/p1718896121997059), the restore from backup behaviour is fixed and refined by this PR:
1. If you restore a profile from disk which has iCloud sync turned off, we will no longer try to claim it on iCloud (bugfix)
2. If you restore a profile that has iCloud sync turned on and claiming on iCloud fails, we will continue to import (bugfix) but Security Center will show a problem
3. Prior to this, when loading the list of iCloud backups (or migrating keychain backups ahead of loading the list), if something goes wrong we now distinguish between three cases:
- Not logged in to iCloud, show "Not logged in to iCloud" in the list
- No internet, show "Network unavailable" in the list
- Other error (very rare), show "Could …
=> Refine Backup Behaviour

RadixWallet/Features/DappInteractionFeature/Children/Completion/Completion+View.swift
Center the content.
Note that we have to make the Success slide up bigger always to account for the possible bottom message to return to the browser.
old:
new: No message
new: Switch back message
=> Center the Success state in the screen

RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor+ViewModifier.swift, RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift, RadixWallet/Features/TransactionReviewFeature/SubmitTransaction/SubmitTransaction.swift
Jira ticket: [ABW-3328](https://radixdlt.atlassian.net/browse/ABW-3328?atlOrigin=eyJpIjoiM2FlOWQwMWRlZDg0NDgxOGExZTA3MDE0OTlmZmFiYjYiLCJwIjoiaiJ9)
Until now, `Home` was in charge of presenting the `NPSSurvey` view whenever the conditions were met (10th successful transaction or 3 months since last time shown). However, if the `DappInteractor` was currently presenting its flow on the root view, we could have an overlap of modal presentations. This causes unexpected behaviors on SwiftUI, by presenting only one of the two modals and leaving modal presentation broken during the app run. 
Trigger the NPS Survey counter increment after completion is dismissed.
You can either run on a fresh install and perform 10 transactions, or just update the logic under `NPSSurveyClient+Live`:
```Swift …
```
=> [ABW-3328] Fix NPSSurvey presentation bug

RadixWallet/Core/FeaturePrelude/AddressView/AddressDetails+View.swift, RadixWallet/Core/FeaturePrelude/AddressView/AddressDetails.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Details/NonFungibleTokenDetails+View.swift
Jira ticket: [ABW-3484](https://radixdlt.atlassian.net/browse/ABW-3484)
Jira ticket: [ABW-3487](https://radixdlt.atlassian.net/browse/ABW-3487)
This PR solves some small UI bugs reported.
Regarding bug [3484](https://radixdlt.atlassian.net/browse/ABW-3484), the solution isn't perfect. This is, if user drags the modal to the top (and hence extend its height), the QR code will still resize while dragging. This is because we want the QR code to take all the available size, and if you increase the modal size then so does the image size. The only way to have it not doing this would be to either:
- prevent the user from dragging the modal => worse UX
- make the QR image size static => we would need to either make the view scrollable, or the QR code smaller enough to fit in every screen …
=> Address Details + NFT Name UI fixes

RadixWallet/Features/CreatePersona/Children/NewPersonaCompletion/NewPersonaCompletion+Reducer.swift, RadixWallet/Features/CreatePersona/Coordinator/CreatePersonaCoordinator+Reducer.swift, RadixWallet/Features/DappInteractionFeature/Children/Login/Coordinator/Login.swift
Jira ticket: [ABW-3477](https://radixdlt.atlassian.net/browse/ABW-3477)
This PR updates the pre-selection logic on the Persona selection screen as follows:
- Pre-select the first Persona when the screen opens or if there isn't a selected Persona.
- Pre-select a newly created Persona if the user creates one within the flow.
https://github.com/radixdlt/babylon-wallet-ios/assets/163979791/abdbdff1-c358-41f8-98d1-7b04ff5bac24
[ABW-3477]: https://radixdlt.atlassian.net/browse/ABW-3477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3477] WalletInteraction - Pre-select Persona

RadixWallet/Core/FeaturePrelude/AddressView/AddressDetails.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Row/NonFungibleAssetRow+View.swift
Jira ticket: [ABW-3501](https://radixdlt.atlassian.net/browse/ABW-3501)
- Fixes the name for the NFT collection on the Assets View
- Fixes the name for the NFT resource on the Address Details view
| - | - |
| <video src=https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/a7b75230-0cec-4ea9-bcbc-7002d4427fd4> | <video src=https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/23b07dd2-6692-465d-a0ff-07062961e7d3> |
[ABW-3501]: https://radixdlt.atlassian.net/browse/ABW-3501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3501] Fix UI issues for NFTs

RadixWallet/Core/FeaturePrelude/AddressView/AddressDetails+View.swift
Jira ticket: [ABW-3484](https://radixdlt.atlassian.net/browse/ABW-3484)
FIxes the position on some devices like iPhone 11 Pro.
| - | - |
| ![Simulator Screenshot - iPhone 11 Pro - 2024-07-10 at 16 30 11](https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/e0d7e9b1-4132-4a8e-ac4f-74d7f1a7bce0) | ![Simulator Screenshot - iPhone 11 Pro - 2024-07-10 at 16 30 47](https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/d94cb595-e928-4392-b3e4-c3b227f2e1bf) |
[ABW-3484]: https://radixdlt.atlassian.net/browse/ABW-3484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3484] Position QR image correctly

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/AppEventsClient/AppEventsClient+Interface.swift, RadixWallet/Clients/HomeCardsClient/HomeCardsClient+Live.swift, RadixWallet/Clients/ResetWalletClient/ResetWalletClient+Interface.swift, RadixWallet/Clients/ResetWalletClient/ResetWalletClient+Live.swift, RadixWallet/Clients/ResetWalletClient/ResetWalletClient+Test.swift, RadixWallet/Features/AppFeature/App+Reducer.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview+Sections.swift
Jira ticket: [ABW-3589](https://radixdlt.atlassian.net/browse/ABW-3589)
This PR solves the bug where the cards for previous user where still displayed after resetting wallet and restoring an old one.
[ABW-3589]: https://radixdlt.atlassian.net/browse/ABW-3589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3589] Home card displaying after reset bug

RadixWallet/Core/FeaturePrelude/Extensions/AttributedString+Extra.swift, RadixWallet/Features/DappInteractionFeature/Children/AccountPermission/AccountPermission+View.swift, RadixWallet/Features/DappInteractionFeature/Children/Login/Row/PersonaRow+View.swift, RadixWallet/Features/DappInteractionFeature/Views/DappHeader.swift
Jira ticket: [ABW-3536](https://radixdlt.atlassian.net/browse/ABW-3536)
This PR updates the UI during Persona login & Account permission flow.
| -- | -- |
| <video src=https://github.com/user-attachments/assets/65b2ad1a-e867-4068-b217-54f25a78d80d> | <video src=https://github.com/user-attachments/assets/3ad14359-296f-4941-8a59-c2162b7e0333> |
[ABW-3536]: https://radixdlt.atlassian.net/browse/ABW-3536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3536] Persona login flow UI adjustments

RadixWallet/Features/ChooseAccounts/ChooseAccounts+View.swift
Jira ticket: [ABW-3607](https://radixdlt.atlassian.net/browse/ABW-3607)
Preselects the account if the dApp is asking for exactly one account and the user has only one account.
[ABW-3607]: https://radixdlt.atlassian.net/browse/ABW-3607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3607] Preselect account on Login

RadixWallet/Clients/SecurityCenterClient/SecurityCenterClient+Live.swift
Jira ticket: [ABW-3490](https://radixdlt.atlassian.net/browse/ABW-3490)
Solves the UI glitch caused by `problem5` showing up and disappearing during an instant.
To reproduce the case easily, you can lower the [retry backup interval](https://github.com/radixdlt/babylon-wallet-ios/blob/164a233d6b532d97cd5135d9607fe90ebd2830e0/RadixWallet/Clients/CloudBackupClient/CloudBackupClient%2BLive.swift#L200) to something like 5-10 seconds. Then, place the device in airplane mode and you will easily see the issue on any account at Home screen.
After doing so and adding some logs for the problems detected by the `SecurityCenterClient`, I could see the following 3 logs almost immediately every time the cloud backup was attempted:
```
[]
[]
[.problem5]
```
As you may see, the client is indicating two …
=> [ABW-3490] Security problems refresh bug

RadixWallet/Core/FeaturePrelude/Extensions/AttributedString+Extra.swift, RadixWallet/Features/DappInteractionFeature/Children/DappOriginVerification/DappInteractionOriginVerification+View.swift, RadixWallet/Features/ScanQR/Children/ScanQR/ScanQR+View.swift
Jira ticket: [ABW-3635](https://radixdlt.atlassian.net/browse/ABW-3635)
Allows the `Text` init for markdown to set a custom font for the emphasized parts.
The following 3 screens are the ones using markdown for a Text. The [first](https://zpl.io/404lWY8) one uses the same font for emphasized part than common, while [second](https://zpl.io/noMqM9A) and [third](https://zpl.io/wyqYOjd) set a different font for the emphasized part.
| DappHeader | Link Connector | Origin verification |
| - | - | - |
| <img src=https://github.com/user-attachments/assets/0ea22aba-ce91-4895-9af1-8cf428c34839 width=200> | <img src=https://github.com/user-attachments/assets/ff4d5d0b-05af-48cf-8bd1-18c9dcd10c10 width=200> |  <img src=https://github.com/user-attachments/assets/e38e9275-8d3a-40b2-a06a-35013b41b2a6 …
=> [ABW-3635] FIx Text with markdown

RadixWallet/Core/DesignSystem/Components/AppTextField.swift, RadixWallet/Features/AssetTransferFeature/Components/TransferAccountList/TransferAccountList+Reducer.swift, RadixWallet/Features/ChooseAccounts/ChooseAccounts+Reducer.swift, RadixWallet/Features/ChooseAccounts/ChooseAccounts+View.swift, RadixWallet/Features/DappInteractionFeature/Children/AccountPermissionChooseAccounts/AccountPermissionChooseAccounts+Reducer.swift, RadixWallet/Features/DappInteractionFeature/Children/AccountPermissionChooseAccounts/AccountPermissionChooseAccounts+View.swift
Jira tickets: 
[ABW-3637](https://radixdlt.atlassian.net/browse/ABW-3637)
[ABW-3633](https://radixdlt.atlassian.net/browse/ABW-3633)
This PR solves:
- bug where users wouldn't be able to scan an account if they had 2 accounts added
- fix UI bug on AppTextField
| -- | -- |
| <video src=https://github.com/user-attachments/assets/43113e1f-b1b6-4630-b969-80ecbaede2f2> | <video src=https://github.com/user-attachments/assets/78556133-8ca3-40de-9ac2-c24374e2fb44> |
| <img src=https://github.com/user-attachments/assets/96ec78b7-2d5d-47dc-bf0f-80ae84c59c5d width=250> | <img src=https://github.com/user-attachments/assets/5bc50bb4-6b8c-4c8b-b63e-8ecb63c6c890 width=250> |
[ABW-3637]: https://radixdlt.atlassian.net/browse/ABW-3637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
=> [ABW-3637] Do not preselect account on Transfer + AppTextField fix

RadixWallet/Features/CardCarousel/CardCarousel+View.swift
Jira ticket: [ABW-3868](https://radixdlt.atlassian.net/browse/ABW-3638)
Removes the Home cards animation to avoid weird bug reported in issue.
Umair mentioned this cannot be consistently reproduced, and in my case I could never reproduce it. Before removing the animation, I've manually modified the code so that the `HomeCardsObserver` would send a cards update every 3 seconds with the same set of cards (in case there was some weird issue in Sargon code that would cause that). Even with that, the animation only happened on first load, as expected, and not every time the cards were set. Therefore, my conclusion is that this is a weird Swift bug and safest thing to do is remove the animation.
=> [ABW-3868] Disable home card animation

RadixWallet/Features/AssetsFeature/AssetsView+Reducer.swift, RadixWallet/Features/AssetsFeature/AssetsView+Update.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Row/NonFungbileAssetRow+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/NonFungibleAssetList+Reducer.swift
Jira ticket: [ABW-3630](https://radixdlt.atlassian.net/browse/ABW-3630)
Fixes an issue where an expanded collection is not updated if it changes after a direct transfer or background refresh.
The solution is to update the collection when the portfolio is updated, but only if the collection is expanded and the `nonFungibleIdsCount` has changed. This ensures the update occurs only when necessary to avoid resetting pagination.
https://github.com/user-attachments/assets/55351d48-f065-4140-95df-cef99af813c1
[ABW-3630]: https://radixdlt.atlassian.net/browse/ABW-3630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3630] Fix NFTs collection background refresh

RadixWallet/Core/FeaturePrelude/AddressView/AddressDetails+View.swift
This PR tops the width/height used for the Address details QR code to be 275 or less.
=> Top QR code width/height

RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Row/NonFungibleAssetRow+View.swift
Jira ticket: [ABW-3651](https://radixdlt.atlassian.net/browse/ABW-3651)
This PR fixes the abbreviation for NFT's localID of an RUID type.
Formatting is handled in [Sargon](https://github.com/radixdlt/sargon/blob/b0f6c8948eb17237414f1bd34ca776fec71a4858/src/profile/v100/address/non_fungible_local_id.rs#L61).
[ABW-3651]: https://radixdlt.atlassian.net/browse/ABW-3651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3651] Fix RUID NFTs local id abbreviation

RadixWallet/Clients/SecurityCenterClient/SecurityCenterClient+Live.swift, RadixWallet/Clients/UserDefaults+Dependency+Extension/UserDefaults+Dependency+Extension.swift
Jira ticket: [ABW-3650](https://radixdlt.atlassian.net/browse/ABW-3650)
This PR solves an issue where a security problem would up for an instant when toggling the balances visibility. 
This issue was introduced when we fixed another similar on https://github.com/radixdlt/babylon-wallet-ios/pull/1207. Basically, we were considering `.started` backups as failures, which helped solved the previous situation. 
However, we shouldn't consider `.started` backups as failures when the last backup was a `.success`: they should only be considered failures when the previous one was a `.failure`. Therefore, the solution is to just ignore `.started` backups for this check.
| -- | -- |
| <video src=https://github.com/user-attachments/assets/12eaf8f7-953f-4d6f-9ad3-37969571862e> | …
=> [ABW-3650] Security state incorrectly updating

RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift
DappInteractor was not hooked to handle the Success screen dismissal by swipe down, thus if there were multiple requests in the queue, the next one was not shown as DappInteractor state still was holding to the Success screen state.
Fix by handling also the dismissal by swipe done.
=> Handle Success screen dismissal by swipe down

RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift
Don't present success screen if there are other transaction in the queue
- A transfer from the Wallet is added.
- A transaction from Gumball Club is added.
- Account update interaction from Gumball Club is added.
Success screen is shown only for the last interaction as there were no other interactions in the queue.
https://github.com/user-attachments/assets/4fa129bd-299c-4ac0-87cf-f45ad4250333
=> Don't present success screen if there are other transaction in the queue

RadixWallet/Features/DappInteractionFeature/Children/Completion/Completion+View.swift, RadixWallet/Features/TransactionReviewFeature/SubmitTransaction/SubmitTransaction+View.swift
Modal wasn't big enough for some font/screen sizes on failure, so we are allowing user to drag up to full screen on such cases.
Also updates spacing between subtitle and TX id to match designs.
=> Allow to drag Submit Transaction modal on failure

RadixWallet/Features/CardCarousel/CardCarousel+View.swift, RadixWallet/Features/HomeFeature/Coordinator/Home+View.swift
Jira ticket: [ABW-3620](https://radixdlt.atlassian.net/browse/ABW-3620)
This PR updates the UI on Home view to match the designs.
Changes to the Account cards are done in https://github.com/radixdlt/babylon-wallet-ios/pull/1216.
| - | - |
| <img width=250 src=https://github.com/user-attachments/assets/fb3a8f35-fe32-4cd3-b336-a6015d05b661> | <img width=250 src=https://github.com/user-attachments/assets/ec0e37b0-cfe7-4fa2-b58a-366ea6de72e2> |
| <img width=250 src=https://github.com/user-attachments/assets/3ec1d98a-479e-4cbe-94f3-1ad0e0bda8c9> | <img width=250 src=https://github.com/user-attachments/assets/77b0d82a-fa0c-48e7-bcb2-e19f24e5ac2a> |
[ABW-3620]: https://radixdlt.atlassian.net/browse/ABW-3620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
=> [ABW-3620] Home view UI adjustments

RadixWallet/Features/DappInteractionFeature/Children/AccountPermission/AccountPermission+View.swift
Jira ticket: [ABW-3539](https://radixdlt.atlassian.net/browse/ABW-3539)
Updates padding for Account Permission screen.
Account cards updates for `AccountPermissionChooseAccounts` are handled [here](https://github.com/radixdlt/babylon-wallet-ios/pull/1216).
| - | - |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-07-17 at 17 45 33](https://github.com/user-attachments/assets/2b8f2857-ede9-4569-be52-8c07012fd311) | ![Simulator Screenshot - iPhone 15 Pro - 2024-07-17 at 17 39 31](https://github.com/user-attachments/assets/944c0351-0872-438c-a6bb-08655a4657b7) |
[ABW-3539]: https://radixdlt.atlassian.net/browse/ABW-3539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3539] UI Adjustments - Account permission

RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Details/NonFungibleTokenDetails+View.swift
Jira ticket: [ABW-3273](https://radixdlt.atlassian.net/browse/ABW-3273)
Updates the time format used for stake claims to be more precise.
Cannot test it on stokenet (as claims last less than 5 minutes), but hardcoded a few epoch values to take the following screenshots.
[ABW-3273]: https://radixdlt.atlassian.net/browse/ABW-3273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3273] Update time format for stake claims

RadixWallet/Clients/OnLedgerEntitiesClient/Helpers/OnLedgerEntitiesClient+CreateEntity.swift
Jira ticket: [ABW-3613](https://radixdlt.atlassian.net/browse/ABW-3613)
Removes nominal amount from fungibles resources sorting criteria.
To test this on stokenet, update [this](https://github.com/radixdlt/babylon-wallet-ios/blob/main/RadixWallet/Clients/AccountPortfoliosClient/AccountPortfoliosClient%2BState.swift#L143) line so that it returns `nil`.
| - | - |
| <img src=https://github.com/user-attachments/assets/c8e6a06e-1530-45cc-bf97-551a60515064 width=250> | <img src=https://github.com/user-attachments/assets/e1706e7d-9080-4d7c-93d1-1d25615712b3 width=250> |
[ABW-3613]: https://radixdlt.atlassian.net/browse/ABW-3613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3613] Fix fungible resources sorting

RadixWallet/Clients/OnLedgerEntitiesClient/Helpers/EntityMetadata+GWMetadata.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Details/NonFungibleTokenDetails+View.swift
Jira ticket: [ABW-3652](https://radixdlt.atlassian.net/browse/ABW-3652)
We should be showing associated tokens and NFTs for dApps, whether showing the dApp from a transaction or the list of approved dApps. It turned out that we filtered them out because the `dapp_definitions` metadata item was parsed in the wrong way, causing it to always appear to be empty. Specifically, the item is sent as a string collection, rather than a collection of `globalAddress`, which is what we expected.
There was also a slight update to the visual appearance of the NFT details screen, to make it work better when showing only a resource, without the individual token.
Since the item `dapp_definition` _is_ being sent as a `globalAddress`, it might seem that the fix should be on the Gateway side, for consistency, …
=> [ABW-3642] Associated Resources in Approved dApps

RadixWallet/Core/DesignSystem/Components/PlainListRow.swift, RadixWallet/Core/DesignSystem/EntitySecurityProblemsView.swift, RadixWallet/Features/DappsAndPersonas/AuthorizedDApps/AuthorizedDApps+View.swift, RadixWallet/Features/DappsAndPersonas/PersonaDetails/PersonaDetails+View.swift, RadixWallet/Features/DappsAndPersonas/Personas/Child/Row/Persona+View.swift
Jira ticket: [ABW-3533](https://radixdlt.atlassian.net/browse/ABW-3533)
Jira ticket: [ABW-3541](https://radixdlt.atlassian.net/browse/ABW-3541)
- Updated Personas List screen
- Updated Persona Profile screen
- Added a new `dappAndPersona` context for `PlainListRow` as those cards have different padding
| Screen Before | Screen After |
| - | - |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-08-01 at 13 04 54](https://github.com/user-attachments/assets/c73e11fc-8593-464f-a380-811e413da59e) | ![Simulator Screenshot - iPhone 15 Pro - 2024-08-01 at 13 02 59](https://github.com/user-attachments/assets/6bf9ee7b-9fde-4436-967f-73804cd5509e) |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-08-01 at 13 05 20](https://github.com/user-attachments/assets/f825dc0e-86f8-4881-b4d2-ba3451efe6ca) | …
=> [ABW-3533, ABW-3541] UI adjustments - Personas List & Persona profile

RadixWallet/Features/AssetTransferFeature/Components/ChooseAccount/ChooseReceivingAccount+Reducer.swift, RadixWallet/Features/AssetTransferFeature/Components/ChooseAccount/ChooseReceivingAccount+View.swift
Jira ticket: [ABW-2072](https://radixdlt.atlassian.net/browse/ABW-2072)
- Hid the "Or: Choose one of your own Accounts" label if there are no more available accounts
- Updated `ChooseReceivingAccount` to use `ObservableState`
| - | - |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-08-05 at 10 05 45](https://github.com/user-attachments/assets/267e1858-37fd-402b-971a-18d3ea8e5a7f)| ![Simulator Screenshot - iPhone 15 Pro - 2024-08-05 at 10 02 09](https://github.com/user-attachments/assets/5401d45c-59a6-4b97-8aef-b710184d7d83) |
[ABW-2072]: https://radixdlt.atlassian.net/browse/ABW-2072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2072] Transfer flow choose account adjustment

RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionFlow.swift
Jira ticket: [ABW-3667](https://radixdlt.atlassian.net/browse/ABW-3667)
I attempted to reproduce this crash but was unsuccessful. According to the logs, the crash occurs when the back button is tapped on the `DappInteractionFlow` and the code tries to remove the last element from `state.path`, which is unexpectedly empty.
This issue has only occurred once for a single user, making it difficult to reproduce. To prevent this crash, I replaced the `removeLast()` method with `popLast()`, as `popLast()` can safely handle an empty collection.
[ABW-3667]: https://radixdlt.atlassian.net/browse/ABW-3667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3667] dApp interaction go back crash

RadixWallet/Clients/OnLedgerEntitiesClient/OnLedgerEntitiesClient+Live.swift, RadixWallet/Features/AccountPreferencesFeature/Children/DevAccountPreferences+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Row/NonFungbileAssetRow+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Row/NonFungibleAssetRow+View.swift
Jira ticket: [ABW-3458](https://radixdlt.atlassian.net/browse/ABW-3458)
This PR updates paging mechanism for NFTs. Our current logic was based on the assumptions that the GW would return pages with the max amount of items, and this could change in the future. In other words, if there are 100 elements to load and we were requesting pages of 29 elements, the app assumed the GW would return 4 pages with `[29, 29, 29, 13]` elements each. However, GW will change and the amount of pages/elements per page won't be fixed.
Play with different NFT collections and sizes to verify the loading happens correctly every time.
[ABW-3458]: https://radixdlt.atlassian.net/browse/ABW-3458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3458] NFT page request updates

RadixWallet/Core/DesignSystem/Components/AppTextField.swift, RadixWallet/Features/ImportMnemonic/ImportMnemonic.swift, RadixWallet/Features/ImportMnemonic/ImportWord/ImportMnemonicWord+View.swift, RadixWallet/Features/ImportMnemonic/ImportWord/ImportMnemonicWord.swift
Jira ticket: [ABW-3655](https://radixdlt.atlassian.net/browse/ABW-3655)
Jira ticket: [ABW-3656](https://radixdlt.atlassian.net/browse/ABW-3656)
Depends on: https://github.com/radixdlt/babylon-wallet-ios/pull/1255
This PR:
- Removes placeholder words from Entry Seed Phrase view
- Allows moving to next seed phrase word when tapping on return key
- Fixes UI issue where word would incorrectly align when showing an error.
https://github.com/user-attachments/assets/8ddd5119-8a8d-4aec-9191-354ebe1814b5
[ABW-3655]: https://radixdlt.atlassian.net/browse/ABW-3655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ABW-3656]: https://radixdlt.atlassian.net/browse/ABW-3656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> [ABW-3655][ABW-3656] Entry seed phrase updates

Aux/Config/Common.xcconfig, RadixWallet/Clients/HTTPClient/HTTPClient+Live.swift, RadixWallet/Core/SharedModels/HTTPURLSessionResponse/HTTPURLSessionResponse.swift, RadixWallet/RadixConnect/RadixConnect/Mobile/RadixConnectMobile.swift
Hotfix for the issue when sometimes the Wallet would fail to validate the dApp after deepLink.
The bug, occurring after several tries
https://github.com/user-attachments/assets/7aabf843-9c71-4927-84cb-bbbe472c07b9
=> Hotfix for dApp validation error

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/GatewaysClient/GatewaysClient+Interface.swift, RadixWallet/Clients/GatewaysClient/GatewaysClient+Live.swift, RadixWallet/Features/GatewaySettingsFeature/Children/AddNewGateway/AddNewGateway+Reducer.swift, RadixWalletTests/Features/GatewaySettingsFeatureTests/GatewaySettingsFeatureTests.swift
Jira ticket: [ABW-3666](https://radixdlt.atlassian.net/browse/ABW-3666)
Depends on https://github.com/radixdlt/sargon/pull/195
This PR updates the usage of Sargon's `hasGateway()` method to correctly handle the throwing case.
https://github.com/user-attachments/assets/9418f0d3-e2a0-41bd-bd93-80065246f24a
[ABW-3666]: https://radixdlt.atlassian.net/browse/ABW-3666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3666] Fix Add gateway crash

RadixWallet/Clients/OnLedgerEntitiesClient/Helpers/EntityMetadata+GWMetadata.swift
From [slack](https://rdxworks.slack.com/archives/C03QFAWBRNX/p1723026826373209)
Some resources, like Instapass Badges, encode the `dapp_definitions` metadata item as a global address collection, which seems like the correct approach, whereas most seem to encode it as a string collection. This PR will make the verification mechanism accept both options, but in the long term goal should probably be to use the global address option.
Started a discussion about it [here](https://rdxworks.slack.com/archives/C031A0V1A1W/p1723040234354979).
=> Be lenient when reading `dapp_definitions`

RadixWallet/Core/SharedModels/Assets/FiatWorth.swift
Jira ticket: [ABW-3062](https://radixdlt.atlassian.net/browse/ABW-3062)
Display nil fiat values without fractional digits
| - | - |
| ![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-05 at 10 59 39](https://github.com/user-attachments/assets/4e14b977-2587-4112-b34d-4fa2781d8582)| ![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-05 at 10 57 59](https://github.com/user-attachments/assets/b06f89e7-e322-45cf-931c-f1a7de86441b) |
[ABW-3062]: https://radixdlt.atlassian.net/browse/ABW-3062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3062] Display nil fiat values without fractional digits

RadixWallet/Features/DappsAndPersonas/AuthorizedDApps/AuthorizedDApps+View.swift, RadixWallet/Features/DappsAndPersonas/AuthorizedDApps/AuthorizedDApps.swift
Jira ticket: [ABW-3675](https://radixdlt.atlassian.net/browse/ABW-3675)
- Fixed the background padding issue
- Refactored `AuthorizedDappsFeature`
| - | - |
| ![simulator_screenshot_7305304E-76AD-436B-99CB-C26D9C147633](https://github.com/user-attachments/assets/e8aeecc0-59d9-48c9-b1b4-9446a8fb3a73) | ![simulator_screenshot_0BD3A4BE-DC91-4D67-B2A8-66CAEE5598F2](https://github.com/user-attachments/assets/3890e987-351b-4a97-a02f-1862754645b9) |
[ABW-3675]: https://radixdlt.atlassian.net/browse/ABW-3675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3675] Approved dApps background issue

RadixWallet/Features/AccountPreferencesFeature/Children/ThirdPartyDeposits/ResourcesList+Reducer.swift, RadixWallet/Features/AccountPreferencesFeature/Children/ThirdPartyDeposits/ResourcesList+View.swift
Jira ticket: [ABW-3676](https://radixdlt.atlassian.net/browse/ABW-3676)
- Fixed the text at the top of the screen for the "Allow/Deny Specific Assets" and "Allow Specific Depositors" screens for accounts that have been recovered via MARS.
- Removed ViewState
| Screen Before | Screen After |
| - | - |
| ![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-07 at 13 01 58](https://github.com/user-attachments/assets/0f412381-6b9e-4d01-80f0-810027447752) | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-07 at 12 55 45](https://github.com/user-attachments/assets/0b129ee7-ea98-4297-9645-860e6888642b) |
| ![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-07 at 13 02 03](https://github.com/user-attachments/assets/7eb1e047-f10a-4b02-9607-822acc4989c3) | ![Simulator Screenshot - iPhone 15 …
=> [ABW-3676] Third party deposits text fix

RadixWallet/Features/AccountDetailsFeature/Coordinator/AccountDetails+Reducer.swift, RadixWallet/Features/AccountDetailsFeature/Coordinator/AccountDetails+View.swift
We had an `onDisappear` that caused a runtime warning. Its purpose was to cancel portfolio fetching that was in flight when leaving the AccountDetails screen, but it does not actually do that, so this PR removes it.
=> Remove onDisappear in AccountDetails

RadixWallet/Core/DesignSystem/Components/WarningView.swift, RadixWallet/Features/TransactionReviewFeature/CustomizeFees/CustomizeFees+View.swift, RadixWallet/Features/TransactionReviewFeature/CustomizeFees/CustomizeFees.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewNetworkFee/TransactionReviewNetworkFee+View.swift
Jira ticket: [ABW-3719](https://radixdlt.atlassian.net/browse/ABW-3720)
(Apparently all changes were lost when GitHub changed the branch for the [previous PR](https://github.com/radixdlt/babylon-wallet-ios/pull/1282))
Adds the warning shown in the screenshot, when a fee payer is selected that wouldn't otherwise be part of the transaction. Also refactors the warning logic, along the lines described [here](https://rdxworks.slack.com/archives/C031A0V1A1W/p1723455294380409).
1. Create three accounts, A, B and C
2. Put some XRD in at least A and C
3. Make a transfer from A to B
4. Select C as fee payer for the transaction
-> The warning should be shown, as per the screenshot
[ABW-3719]: https://radixdlt.atlassian.net/browse/ABW-3719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
=> ABW-3719 Warn When Linking New Accounts (again)

RadixWallet/Features/TransactionReviewFeature/TransactionReviewNetworkFee/TransactionReviewNetworkFee+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewNetworkFee/TransactionReviewNetworkFee.swift
Jira ticket: [ABW-3743](https://radixdlt.atlassian.net/browse/ABW-3743)
Shows the fiat value of transaction fees.
[ABW-3743]: https://radixdlt.atlassian.net/browse/ABW-3743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3743] Show fiat value of Transaction fees

RadixWallet/Features/AppFeature/SceneDelegate.swift
Jira tickets: [ABW-3738](https://radixdlt.atlassian.net/browse/ABW-3738), [ABW-3739](https://radixdlt.atlassian.net/browse/ABW-3739)
This PR updates the logic so that the privacy overlay is displayed only after the app enters the background. This ensures that when the app is inactive (e.g., during a biometric check), the privacy overlay will not be shown.
https://github.com/user-attachments/assets/1f7eea9b-1aae-4741-b8e3-ab9aac95940b
[ABW-3738]: https://radixdlt.atlassian.net/browse/ABW-3738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ABW-3739]: https://radixdlt.atlassian.net/browse/ABW-3739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3739] Show the Privacy overlay only after the app enters the background

RadixWallet/Features/AccountDetailsFeature/Coordinator/AccountDetails+View.swift
Jira ticket: [ABW-3574](https://radixdlt.atlassian.net/browse/ABW-3574)
Fixes the empty space at the top of the AccountView screen
| iOS 18 Before | iOS 18 After |
| - | - |
| ![simulator_screenshot_349B20BB-4980-42BF-B6AF-0CCF8389A2E9](https://github.com/user-attachments/assets/5572dc54-9188-4abd-a123-bcc7425de6f4) | ![simulator_screenshot_DCFFA317-72F6-4201-B758-2711AF95DA09](https://github.com/user-attachments/assets/3d3b67ca-82df-4c14-820a-6344483d9e15)|
| iOS 17.4 Before | iOS 17.4 After |
| - | - |
| ![simulator_screenshot_6ED815F9-69DC-49BE-9D88-CCAFD73B738A](https://github.com/user-attachments/assets/27a14a5d-4259-4fa1-be41-cf16712a28b1) | ![simulator_screenshot_3E548D32-D9F8-494A-9674-EFEA24074B38](https://github.com/user-attachments/assets/47a897b3-89a0-445f-a3fe-11ea09b7e64b) | …
=> [ABW-3574] Fix AccountView screen empty space

RadixWallet/Clients/GatewayAPI/CodeGen/Generated/ProgrammaticScryptoSborValueEnum.swift
Jira ticket: ABW-3768
The property `variantId` on `ProgrammaticScryptoSborValueEnum` will soon be sent as a String by Gateway, but this is not implemented yet in production on mainnet, so this PR brings back some compatibility code that handles both the Int and String versions of the property.
- Open account details, this should work for both Mainnet and Stokenet
=> [ABW-3768] Bring back compatibility decoding of variant_id

RadixWallet/Features/HomeFeature/Children/NPSSurvey/NPSSurvey+View.swift
Fixes a misplacement of the `CloseButton`.
| - | - |
| <img width=250 src=https://github.com/user-attachments/assets/8d30b5e2-2a5e-4cf6-841f-52604d5bf189> | <img width=250 src=https://github.com/user-attachments/assets/6970c1b2-db1a-4f96-9d6e-af1892c81142> |
=> Fix close button position on NPS survey

RadixWallet/Features/TransactionReviewFeature/TransactionReviewNetworkFee/TransactionReviewNetworkFee+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewNetworkFee/TransactionReviewNetworkFee.swift
Jira ticket: [ABW-3750](https://radixdlt.atlassian.net/browse/ABW-3750)
This PR fixes an issue introduced in https://github.com/radixdlt/babylon-wallet-ios/pull/1292, where the fiat value for the price would show an infinite loading spinner after updating such price.
https://github.com/user-attachments/assets/32e8acf3-14ab-4d4b-aa13-627560ed101d
[ABW-3750]: https://radixdlt.atlassian.net/browse/ABW-3750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3750] Fix infinite loading on fiat price after updating TX fee

RadixWallet.xcodeproj/project.pbxproj, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift
For manifests without any withdrawals or deposits, the Wallet was incorrectly showing the Account Linking error.
https://github.com/user-attachments/assets/b453ecb9-809b-418a-914a-6b6d0159529a
=> Fix AccountLinking warning for manifests without withdrawals/deposits

RadixWallet/Features/CreatePersona/Children/Introduction/IntroductionToPersonas.swift
Jira ticket: [ABW-3776](https://radixdlt.atlassian.net/browse/ABW-3776)
This PR fixes the issue where users could not create a new persona by explicitly declaring the `body`. This was necessary due to a conflict between our `FeatureReducer` protocol and the `@Reducer` macro.
[ABW-3776]: https://radixdlt.atlassian.net/browse/ABW-3776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3776] Unable to create new persona fix 

RadixWallet/Features/HomeFeature/Coordinator/Home.swift
Jira ticket: [ABW-3779](https://radixdlt.atlassian.net/browse/ABW-3779)
This PR solves a UI bug caused on Home after hiding an account on mainnet.
| - | - |
| <video src=https://github.com/user-attachments/assets/3ee79f3a-cd12-4d66-8dbb-47f5170ccf00> | <video src=https://github.com/user-attachments/assets/26789baa-ccc1-47d7-b3e7-07fbe8577df3> |
[ABW-3779]: https://radixdlt.atlassian.net/browse/ABW-3779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3779] Fix Home not showing resources after hiding Account 

RadixWallet/Features/SettingsFeature/Preferences/DefaultDepositGuarantees/DefaultDepositGuarantees+View.swift
Jira ticket: [ABW-3789](https://radixdlt.atlassian.net/browse/ABW-3789)
Adds missing ℹ️  button to Default deposit guarantees
https://github.com/user-attachments/assets/6e03aca8-f64a-48a5-b709-efc8043f4308
[ABW-3789]: https://radixdlt.atlassian.net/browse/ABW-3789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3789] Add info button to default deposit guarantees

RadixWallet/Features/AccountPreferencesFeature/Children/ThirdPartyDeposits/ResourcesList+View.swift, RadixWallet/Features/AssetTransferFeature/Components/TransferAccountList/ReceivingAccount/ReceivingAccount+Reducer.swift, RadixWallet/Features/AssetTransferFeature/Components/TransferAccountList/TransferAccountList+Reducer.swift
This PR fixes an issue where the app would also show a 400 error when reviewing a transfer of at least one NFT to an external account.
Also, it adds vertical spacing among the elements of `Allow/Deny Specific Assets` view, after they were migrated to use the same UI than `Hidden Assets` view.
https://github.com/user-attachments/assets/a2c6cbc2-b862-4787-96c4-23fac2664ba4
| - | - |
| <img src=https://github.com/user-attachments/assets/5e08d9b6-7a89-4c66-8a18-a105d1cc0a13 width=200> | <img src=https://github.com/user-attachments/assets/d7289a64-b579-428d-94ea-5b6a9f31ef59 width=200> |
=> Fix validation of NFT tranfers to external accounts

RadixWallet/Clients/AccountPortfoliosClient/AccountPortfoliosClient+State.swift
The wallet was mistakenly calculating the worth of stake unit resource amount instead of the xrd redemption value.
This multiplies the stake unit resource amount with the XRD price
This multiplies the xrd redemption with xrd price
=> Fix stake unit resource redemption value

Aux/en.lproj/InfoPlist.strings
As reported by Umair in [Slack](https://rdxworks.slack.com/archives/C03QFAWBRNX/p1727800499569819), it isn't possible to connect to a Linked Connector on iOS 18.
Adding the missing key to `InfoPlist.strings` fixes it.
=> Fix Linked Connectors on iOS 18

RadixWallet/Features/TransactionReviewFeature/TransactionReview+View.swift
Jira ticket: [ABW-3798](https://radixdlt.atlassian.net/browse/ABW-3798)
Updates the dApp icon position and size on TX reviews.
| - | - |
| <img src=https://github.com/user-attachments/assets/1d22bbf9-5514-4e40-9ccc-5a91a3f5b483 width=200> | <img src=https://github.com/user-attachments/assets/82296cea-eb1b-49ec-a1ad-4be999cfbf14 width=200> |
[ABW-3798]: https://radixdlt.atlassian.net/browse/ABW-3798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3798] Update dApp icon position/size on TX review

RadixWallet/Clients/P2PLinksClient/P2PLinksClient+Interface.swift, RadixWallet/Features/FactorSourceAccess/FactorSourceAccess+View.swift, RadixWallet/Features/FactorSourceAccess/FactorSourceAccess.swift, RadixWallet/Features/Signing/Children/SignWithFactorSource.swift
Jira ticket: [ABW-3581](https://radixdlt.atlassian.net/browse/ABW-3581)
Inform users when they attempt to access a Ledger factor source but the wallet isn't connected to any connector extension. 
Also, improves the UX by removing a glitch where the ledger name wouldn't show up for an instant.
| - | - |
| <video src=https://github.com/user-attachments/assets/65ba3267-6b8b-428d-ac30-9b021bdfc454> | <video src=https://github.com/user-attachments/assets/902b2f3a-5ccf-41e2-8597-51bac5507a24> |
[ABW-3581]: https://radixdlt.atlassian.net/browse/ABW-3581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3581] Inform users when signing with Ledger without P2PLinks

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/AccountLockersClient/AccountLockersClient+Live.swift, RadixWallet/Clients/FaucetClient/FaucetClient+Live.swift, RadixWallet/Clients/GatewayAPI/GatewayAPIClient/GatewayAPIClient+Interface.swift, RadixWallet/Clients/GatewayAPI/GatewayAPIClient/GatewayAPIClient+Live.swift, RadixWallet/Clients/GatewayAPI/GatewayAPIClient/GatewayAPIClient+Mock.swift, RadixWallet/Clients/SubmitTransactionClient/SubmitTransactionClient+Interface.swift, RadixWallet/Clients/SubmitTransactionClient/SubmitTransactionClient+Live.swift, RadixWallet/Clients/SubmitTransactionClient/SubmitTransactionClient+Test.swift, RadixWallet/Clients/TransactionClient/Models/TransactionModels.swift, RadixWallet/Clients/TransactionClient/TransactionClient+Live.swift, RadixWallet/Features/AccountPreferencesFeature/Children/ThirdPartyDeposits/ThirdPartyDeposits+Reducer.swift, RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift, RadixWallet/Features/TransactionReviewFeature/SubmitTransaction/SubmitTransaction+View.swift, RadixWallet/Features/TransactionReviewFeature/SubmitTransaction/SubmitTransaction.swift, RadixWalletTests/Clients/FaucetClientTests/FaucetClientTests.swift
Jira ticket: [ABW-3858](https://radixdlt.atlassian.net/browse/ABW-3858)
Depends on https://github.com/radixdlt/babylon-wallet-ios/pull/1234
Use SargonOS to submit a transaction and then poll for its status.
Also, fixes an issue where the `Completion.View` was displayed full screen on iOS 18.
https://github.com/user-attachments/assets/d1416f64-5f07-44f7-a454-985b30fbc413
| - | - |
| <img src=https://github.com/user-attachments/assets/86fe1861-7f92-483d-944e-97f05d4111d2 width=250> | <img src=https://github.com/user-attachments/assets/0d7284d8-e609-4cfc-8509-21efd7bec32c width=250> |
[ABW-3858]: https://radixdlt.atlassian.net/browse/ABW-3858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3858] Submit transaction and poll its status via SargonOS

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/FactorSourcesClient/FactorSourcesClient+Live.swift, RadixWallet/Clients/GatewayAPI/GatewayAPIClient/GatewayAPIClient+Interface.swift, RadixWallet/Clients/GatewayAPI/GatewayAPIClient/GatewayAPIClient+Live.swift, RadixWallet/Clients/GatewayAPI/GatewayAPIClient/GatewayAPIClient+Mock.swift, RadixWallet/Clients/SubmitTransactionClient/SubmitTransactionClient+Interface.swift, RadixWallet/Clients/TransactionClient/Models/TransactionFailure.swift, RadixWallet/Clients/TransactionClient/Models/TransactionModels.swift, RadixWallet/Clients/TransactionClient/TransactionClient+Live.swift, RadixWallet/Clients/TransactionHistoryClient/TransactionHistoryClient+Interface.swift, RadixWallet/Clients/TransactionHistoryClient/TransactionHistoryClient+Live.swift, RadixWallet/Core/SharedModels/LedgerIdentifiable.swift, RadixWallet/Features/DappInteractionFeature/Children/Completion/Completion+View.swift, RadixWallet/Features/DappInteractionFeature/Children/Completion/Completion.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionCoordinator.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionFlow.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionModels.swift, RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift, RadixWallet/Features/TransactionHistory/TransactionHistory+Reducer.swift, RadixWallet/Features/TransactionHistory/TransactionHistory+TableView.swift, RadixWallet/Features/TransactionReviewFeature/SubmitTransaction/SubmitTransaction+View.swift, RadixWallet/Features/TransactionReviewFeature/SubmitTransaction/SubmitTransaction.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift, RadixWalletTests/Clients/FaucetClientTests/FaucetClientTests.swift, RadixWalletTests/Features/TransactionReviewFeatureTests/CustomizeFeePayerTests.swift
Jira ticket: [ABW-3862](https://radixdlt.atlassian.net/browse/ABW-3862)
This PR uses SargonOS to get the Transaction Preview.
The images on the left show how `main` branch currently shows Transaction Review, while the images on the right repeat the same flow but using Sargon OS to get the preview. It is a good thing that they look the same :)  
| - | - |
| <img width=200 src=https://github.com/user-attachments/assets/2dcbab01-1bcd-4aec-8ae8-18040de02442> | <img width=200 src=https://github.com/user-attachments/assets/b0532e47-98e9-4d1e-9ab0-5fe4ea13a2ef> |
| <img width=200 src=https://github.com/user-attachments/assets/818f071b-b548-43ad-bb4e-73028e4b7dd7> | <img width=200 src=https://github.com/user-attachments/assets/15883d83-d310-4566-b860-1b75679404 …
=> [ABW-3862] Get Transaction Preview from SargonOS

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/DappInteractionClient/DappInteractionClient+Interfce.swift, RadixWallet/Clients/DappInteractionClient/DappInteractionClient+Live.swift, RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift, RadixWallet/Features/PreAuthorizationReview/PreAuthorizationReview.swift
Jira ticket: [ABW-3913](https://radixdlt.atlassian.net/browse/ABW-3913)
When handling a PreAuthorization request, check its status to see if it is valid.
[ABW-3913]: https://radixdlt.atlassian.net/browse/ABW-3913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3913] Pre validate the expiration of PreAuthorization requests

RadixWallet/Clients/TransactionClient/Models/TransactionFailure.swift, RadixWallet/Clients/TransactionClient/TransactionClient+Live.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift
- If the transaction analysis fails with `FailedTransactionPreview`, we should send back the error message that Sargon determines (instead of `"Unknown reason"`).
- Stop [appending](https://github.com/radixdlt/babylon-wallet-ios/blob/main/RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift#L288-L291) `ET failed to generate TX review` before any error parsed during TX preview loading.  
- If the error is an unknown `CommonError` (meaning a specific message cannot be determined for it for this flow), include its code in the message sent back to the dApp.
- Updates error messages to be more descriptive
Before
```
"message": "ET failed to generate TX review: Failed to retrive TX receipt from gateway: Unknown reason"
"message": "ET failed to generate TX review: Transaction …
```
=> [fix] Send correct error message from TX preview failure

RadixWallet/Clients/OnboardingClient/OnboardingClient+Interface.swift, RadixWallet/Clients/OnboardingClient/OnboardingClient+Live.swift, RadixWallet/Clients/ProfileStore/ProfileStore.swift, RadixWallet/Features/SplashFeature/Splash.swift
Fixed the profile access on Profile store to avoid crashing the app if some parent task was cancelled.
=> Fix profile access on ProfileStore

.github/workflows/cd.yml, .github/workflows/ci.yml
GH removed Xcode 16 from Macos-14 images because policy -> https://github.com/actions/runner-images/issues/10703.
=> Update GH actions to use macos 15

RadixWallet/Clients/GatewayAPI/GatewayAPI+Utils.swift, RadixWallet/Clients/GatewayAPI/GatewayAPIClient/GatewayAPIClient+Live.swift, RadixWallet/Clients/HomeCardsClient/HomeCardsClient+Live.swift, RadixWallet/Clients/PasteboardClient/PasteboardClient+Live.swift, RadixWallet/Clients/SecureStorageClient/SecureStorageClient+Live.swift, RadixWallet/Clients/TransactionClient/Models/TransactionModels.swift, RadixWallet/Clients/TransactionClient/TransactionClient+Live.swift, RadixWallet/Features/AppFeature/Overlay/HUD+View.swift, RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift, RadixWallet/Prelude/Extensions/AsyncExtension+Sendable.swift, RadixWallet/Prelude/Extensions/BigUInt+Extra.swift, RadixWallet/Prelude/Extensions/CryptoKit/PublicKey+Extensions.swift, RadixWallet/Prelude/Extensions/Either+Extra.swift, RadixWallet/Prelude/Extensions/NonEmpty+Extra.swift, RadixWallet/Prelude/JSON/JSONDecoder+Live.swift, RadixWallet/Prelude/JSON/JSONEncoder+Live.swift, RadixWallet/RadixConnect/RadixConnect/RTC/Infrastructure/AsyncWebSocket.swift, RadixWallet/RadixConnect/RadixConnect/RTC/Infrastructure/WebRTC/RTCDataChannel+Delegate.swift, RadixWallet/RadixConnect/RadixConnect/RTC/Infrastructure/WebRTC/RTCPeerConnection+PeerConnection.swift, RadixWallet/RadixConnect/RadixConnectModels/Types.swift, RadixWalletTests/Clients/TransactionClientTests/TransactionClientTests.swift
When determining fee payer take into account the withdrawn XRD amount for the fee payer candidates from which withdraw is happening.
This is very important in the context of account deletion, when all XRDs will be transferred, so then the Wallet should try to use the account into which the deposit is happening.
https://github.com/user-attachments/assets/bd430119-d924-4221-ba5e-a4dc2a2a6e72
=> Determine fee payer update

RadixWallet/Clients/RadixConnectClient/RadixConnectClient+Interface.swift, RadixWallet/Clients/RadixConnectClient/RadixConnectClient+Live.swift, RadixWallet/Clients/RadixConnectClient/RadixConnectClient+Test.swift, RadixWallet/Features/AccountRecoveryScan/Children/AccountRecoveryScanInProgress/AccountRecoveryScanInProgress+View.swift, RadixWallet/Features/AccountRecoveryScan/Children/AccountRecoveryScanInProgress/AccountRecoveryScanInProgress.swift, RadixWallet/Features/AccountRecoveryScan/Coordinator/AccountRecoveryScanCoordinator.swift, RadixWallet/Features/MainFeature/Main+Reducer.swift, RadixWalletTests/Features/MainFeatureTests/MainFeatureTests.swift
https://radixdlt.atlassian.net/browse/ABW-4004
Fix the places that did access the profile when it was not present yet:
- RadixConnectClient notifying CE with updated right after a profile is selected for import.
- Account recovery scan from the onboarding trying to get appearance id from the Profile
=> Fix crash caused by early profile access

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/PreAuthorizationClient/PreAuthorizationClient+Interface.swift, RadixWallet/Clients/PreAuthorizationClient/PreAuthorizationClient+Live.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionCoordinator.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionFlow.swift, RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift, RadixWallet/Features/PreAuthorizationReview/PollPreAuthorizationStatus/PollPreAuthorizationStatus.swift, RadixWallet/Features/PreAuthorizationReview/PreAuthorizationReview.swift
Jira ticket: [ABW-4001](https://radixdlt.atlassian.net/browse/ABW-4001)
Updates response to include `SubintentHash` and `expirationTimestamp`, which allows us to remove the `PreAuthData` helper struct we moved along `DappInteractor` (and children).
Play with Anthic test app and verify everything works as expected.
[ABW-4001]: https://radixdlt.atlassian.net/browse/ABW-4001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-4001] Update PreAuthorization models

RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Children/SelectBackup/SelectBackup+Reducer.swift
The Wallet did hang indefinitely when importing an encrypted profile. 
Could not find a strong reason as to why the bug is happening. Seems to be caused by SwiftUI issue of cancelling the view task, in this case ImportMnemonicsFlowCoordinator's view, when the previews view is not yet fully dismissed.
Add a small delay fixes the issue.
https://github.com/user-attachments/assets/a72b3100-12f6-4096-959f-4bba13022049
=> Fix import encrypted profile hang

RadixWallet/Features/InteractionReview/Sections/Sections+ManifestSummary.swift
Jira ticket: [ABW-3984](https://radixdlt.atlassian.net/browse/ABW-3984)
Solves an issue where we weren't checking for NFT visibility under Manifest Summary.
1. Connect to [sample dApp](https://d1vuj67scmz8qj.cloudfront.net/)
2. Send a Pre Authorization with the instructions detailed below
3. Hide the `Abandon` collection
4. Close the Pre Authorization and send it again
5. You should see the expected warning under the collection
```
CALL_METHOD
Address("account_tdx_2_129nje53m7dn405snw9e8sl72ej334r7dudl6zwvx6cn92efueqyjsd")
"withdraw"
Address("resource_tdx_2_1n2lj0rk7pye8h2cxs347lf70ksyzwaez0mjkssccfthp6m408hfny7")
Decimal("5")
;
CALL_METHOD
Address("account_tdx_2_129rfcz44zxflyaf6d65fdvaqtk5rlvdu8nzek2nz435zknhqure2xl")
"deposit_batch"
Expression("ENTIRE_WORKTOP")
;
YIELD_TO_PARENT;
``` …
=> [ABW-3984] Fix NFT collection hidden warning on Pre Authorization

RadixWallet/Core/DesignSystem/Components/AssetIcon.swift, RadixWallet/Core/DesignSystem/ToggleView.swift, RadixWallet/Features/AccountPreferencesFeature/AccountPreferences+View.swift, RadixWallet/Features/AccountPreferencesFeature/Children/ThirdPartyDeposits/ThirdPartyDeposits+View.swift, RadixWallet/Features/InteractionReview/Components/RawManifestView.swift, RadixWallet/Features/SecurityCenterFeature/SecurityFactors/SecurityFactors+Reducer.swift, RadixWallet/Features/SecurityCenterFeature/SecurityFactors/SecurityFactors+View.swift, RadixWallet/Features/SettingsFeature/Preferences/Preferences+View.swift, RadixWallet/Features/SettingsFeature/Settings+View.swift, RadixWallet/Features/SettingsFeature/SettingsRow.swift, RadixWallet/Features/SettingsFeature/Troubleshooting/Troubleshooting+View.swift
Jira ticket: [ABW-3918](https://radixdlt.atlassian.net/browse/ABW-3918)
This PR updates the Security Factors screen to match new [design](https://zpl.io/4E0kMQ4).
[Link](https://drive.google.com/file/d/1xLIKXTIgnrUJ_zMFpdDmMKWc2SR87HrR/view?usp=sharing)
[ABW-3918]: https://radixdlt.atlassian.net/browse/ABW-3918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3918] Security Factors redesign

RadixWallet/Features/CreateAccount/Coordinator/CreateAccountCoordinator+Models.swift, RadixWallet/Features/CreateAccount/Coordinator/CreateAccountCoordinator+Reducer.swift, RadixWallet/Features/OnboardingFeature/Coordinator/OnboardingCoordinator+Reducer.swift
Fixes bug where users wouldn't be able to create a Profile if they cancelled the creation flow in the middle.
[Reference](https://rdxworks.slack.com/archives/C031A0V1A1W/p1733932355719239)
=> Wait until first account creation to create Profile

Aux/Config/Common.xcconfig, RadixWallet/Clients/AccountPortfoliosClient/AccountPortfoliosClient+State.swift, RadixWallet/Features/AccountPreferencesFeature/Children/DeleteAccount/DeleteAccountConfirmation+Reducer.swift, RadixWallet/Features/CreateAccount/Coordinator/CreateAccountCoordinator+Models.swift, RadixWallet/Features/CreateAccount/Coordinator/CreateAccountCoordinator+Reducer.swift, RadixWallet/Features/OnboardingFeature/Coordinator/OnboardingCoordinator+Reducer.swift
As described in [Slack](https://rdxworks.slack.com/archives/C031A0V1A1W/p1733852936003809), when doing an account deletion, the wallet isn't paying attention to hidden assets when checking to see if the account has anything in it to move. This only happens if the mentioned account only has assets that are hidden.
This hotfix solves this issue by checking for hidden assets as well.
=> Hotfix for delete account with hidden assets only

Aux/Config/Common.xcconfig, RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/DeviceFactorSourceClient/DeviceFactorSourceClient+Interface.swift, RadixWallet/Clients/FactorSourcesClient/FactorSourcesClient+Live.swift, RadixWallet/Clients/OnLedgerEntitiesClient/Helpers/OnLedgerEntitiesClient+CreateEntity.swift, RadixWallet/Clients/PreAuthorizationClient/PreAuthorizationClient+Live.swift, RadixWallet/Clients/TransactionClient/TransactionClient+Live.swift, RadixWallet/Core/SharedModels/Assets/ResourceAmount.swift, RadixWallet/Features/AssetsFeature/Components/HelperViews/ResourceBalance/ResourceBalance.swift, RadixWallet/Features/ClaimWallet/ClaimWallet+Reducer.swift, RadixWallet/Features/ClaimWallet/ClaimWallet+View.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionFlow.swift, RadixWallet/Features/DebugInspectProfile/InspectProfile+View.swift, RadixWallet/Features/PreAuthorizationReview/PreAuthorizationReview.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift, RadixWalletTests/TestExtensions/TestUtils.swift
- Allow unknown accounts that require signature in manifest -> https://github.com/radixdlt/sargon/pull/307.
- Update Wallet Transfer screen to use Reset Wallet look and logic as for factory reset -> [demo](https://drive.google.com/file/d/1dDQT_ALSCx_4tD-sLFwgtCSkDiXyLm-3/view?usp=sharing)
=> 1.11.3 hotfix
