radixdlt/babylon-wallet-ios

App/Config/Common.xcconfig
Bump version to `1.0.2` so that we can submit it to Apple for review.
=> Bump version to 1.0.2

App/Config/Common.xcconfig
=> Bump version to 1.0.3

Sources/EngineKit/HashableExtensions.swift, Sources/Features/SettingsFeature/AccountSecurity/AccountSecurity+View.swift, Tests/Features/GatewaySettingsFeatureTests/GatewaySettingsFeatureTests.swift
Just a cleanup of some unwanted code styles from https://github.com/radixdlt/babylon-wallet-ios/pull/817
=> Cleanup of HashableExtension

Package.swift, Sources/Clients/GatewayAPI/GatewayAPIClient+Extension.swift, Tests/Clients/GatewayAPITests/GatewayAPITests.swift, Tests/Clients/GatewayAPITests/TestVectors/behaviors1.json, Tests/Clients/GatewayAPITests/TestVectors/behaviors2.json
- Adds test for `extractBehaviors()`
- Adds a thorough doc comment to that function
- Simplifies the way the function works
This should not change how the app behaves, so the way to test it is to look at various resources and make sure the lists behaviors are still correct
=> Testing behaviors

.github/workflows/cd.yml, .github/workflows/ci.yml
Stop archiving part of CI used for PRs. Only unit test.
=> stop archive when unit testing

RadixWallet.xcodeproj/project.pbxproj, RadixWallet/EngineKit/RadixEngineToolkitError+Description.swift
Display a the error description for RET errors.
=> Radix Engine Toolkit error description

RadixWallet/Clients/FaucetClient/FaucetClient+Live.swift, RadixWallet/Cryptography/SLIP10/SLIP10/Path/HD+Path.swift, RadixWallet/Features/AccountPreferencesFeature/Children/ThirdPartyDeposits/ResourcesList+Reducer.swift, RadixWallet/Features/Signing/Children/Factors/SignWithFactorSourcesOfKindDevice/SignWithFactorSourcesOfKindDevice.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift
`brew update && brew upgrade swiftformat`
Ensure you have `0.52.8`
=> update swiftformat to 0.52.8

RadixWallet/Features/TransactionReviewFeature/SubmitTransaction/SubmitTransaction+View.swift
Jira ticket: https://radixdlt.atlassian.net/browse/ABW-2082
Fix iOS 17 animation.
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/dbf9b6de-1d9b-4341-87a3-cf3debd5c5e0
=> [ABW-2082] Transaction completion animation fix

RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewGuarantees/TransactionReviewGuarantees.swift
Jira ticket: https://radixdlt.atlassian.net/browse/ABW-2490
Update Gurantees to update the gurantee amount value while changing the guarantee percentage.
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/699fd2be-f957-4707-b7ab-3a3a66abfaf1
=> [ABW-2490] - Update guarantee amount while changing the percentage

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sorry about this! And thanks to @umair-rdx for reporting it. It's all good now.
=> Fix NavigationStack animations on iOS 17.1

Aux/Config/Common.xcconfig
=> 1.1.0 bump

.github/workflows/ci.yml
This PR solves problem of not running CI if normal PR is opened.
=> [DO-1999] fix PR triggers

Aux/Config/Common.xcconfig
=> 1.2.0 version bump

RadixWallet/Clients/ProfileStore/ProfileStore.swift
=> Documentation only

Aux/Config/Common.xcconfig
=> 1.3.0 Bump

RadixWallet/Features/AccountRecoveryScan/Children/AccountRecoveryScanInProgress/AccountRecoveryScanInProgress.swift
Add a small delay before showing the slide up.
=> DerivePublicKeys slide up issue

RadixWallet/Features/SettingsFeature/AccountSecurity/ManualAccountRecoveryScan/ManualAccountRecoveryCoordinator+View.swift
=> Fix account recovery title

RadixWallet/Features/HomeFeature/Children/AccountRow/Home+AccountRow+View.swift
Jira ticket: ABW-2666
The asset icons and labels in the account cards on the home screen were not entirely correct. This PR adds a border to the individual non-fungible assets, plus a white background behind the pool unit and nft icons.
=> [ABW-2666] New Icon Appearance

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/EngineKit/HashableExtensions.swift
Brings in the stake claim data for unstaking transactions.
=> RET 1.0.9 update

RadixWallet/Clients/OnLedgerEntitiesClient/Helpers/OnLedgerEntitiesClient+CreateEntity.swift, RadixWallet/Clients/OnLedgerEntitiesClient/OnLedgerEntitiesClient+Interface.swift, RadixWallet/EngineKit/IsXRDResource.swift, RadixWallet/EngineKit/ManifestBuilder/CustomTransactionManifests.swift, RadixWallet/EngineKit/ReviewedTransaction.swift, RadixWallet/Features/AssetsFeature/AssetsView+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Details/NonFungibleTokenDetails+View.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/Components/StakeClaimNFTsView.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/Components/StakeSummaryView.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/StakeUnitList.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview+Sections.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewAccount/TransactionReviewAccount+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewAccount/TransactionReviewAccount.swift
Stake claim Transaction Review.
- Identify the stake claim NFT and populate it in TX Review.
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/3ba59170-5b20-4ded-b7bb-016788f75b6a
=> TX Review Stake claim

RadixWallet/Features/HomeFeature/Coordinator/Home.swift
JIRA: [ABW-2869](https://radixdlt.atlassian.net/browse/ABW-2869)
Point to the new URL.
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/f3faebc1-5e16-4d26-99c1-59f76ba54701
[ABW-2869]: https://radixdlt.atlassian.net/browse/ABW-2869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Radix Banner URL

RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Details/NonFungibleTokenDetails+View.swift
Detect and display properly the Instant NFT Data type.
A given NFT Data field is consider an Instant type if:
- The kind is an I64.
- The type_name is Instant.
- The value is a valid i64.
Formatted the date with system's `format` to inherit all of the users settings regarding date formatting, there are no requirements to display the `Instant` NFT Data in a particular, fixed format.
=> Formatted Instant NFT Data

Aux/Config/Common.xcconfig
=> 1.4.0 version bump

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Updated to latest available WebRTC version - M120.
=> Update WebRTC to M120

RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift
Show the transferred amount in asset details from TX Review.
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/fc877c56-bb63-4200-822a-03271c5917d5
=> TX Review show amount in Asset details

RadixWallet/Core/DesignSystem/Components/PoolUnitView.swift
Jira ticket: [ABW-2917](https://radixdlt.atlassian.net/browse/ABW-2917)
Complements / depends on / relates to #link to other PR
This PR solves / fixes / adds / includes functionality 1 and functionality 2.
Additional notes.
1. Step 1
2. Step 2
3. Verify
1. Step 1
2. Step 2
3. Verify
| - | - |
| paste link here | paste link here |
paste link here
[ABW-2917]: https://radixdlt.atlassian.net/browse/ABW-2917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2917] Scaling fix

RadixWallet/Features/AssetsFeature/Components/StakeUnitList/Components/LiquidStakeUnitView.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/StakeUnitList.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewAccount/TransactionReviewAccount+View.swift
#Demo
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/eb9ba220-1835-402f-b841-16ebdc5c9a24
=> Transaction value for LSUs

RadixWallet/Features/AssetsFeature/Components/StakeUnitList/Components/LiquidStakeUnitView.swift
Add back the removed selection box.
=> Show selection box for stake units

Aux/Config/Common.xcconfig
=> 1.5.0 version bump

RadixWallet/Features/ImportMnemonic/ImportWord/ImportMnemonicWord+View.swift
Disable autofocus for now until proper fix.
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/8b800061-7f72-433c-a913-49616949ce15
=> Import mnemonic keyboard behaviour fix

.github/workflows/ci.yml, .github/workflows/release.yml
`--json-file-output parameter` stopped working properly but the same effect can be achieved with stdout redirect `>`
=> ci: restore snyk sbom

RadixWallet/Features/AccountDetailsFeature/Coordinator/AccountDetails+View.swift
Jira ticket: [ABW-3019](https://radixdlt.atlassian.net/browse/ABW-3019)
Includes a fix for the Jira ticket + spacing fixes to conform to design specs.
| - | - |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-03-25 at 12 00 41](https://github.com/radixdlt/babylon-wallet-ios/assets/163979791/1bc73870-73e8-42b2-ae5b-082551d33a2c) | ![Simulator Screenshot - iPhone 15 Pro - 2024-03-25 at 12 00 47](https://github.com/radixdlt/babylon-wallet-ios/assets/163979791/e25bbf59-41ee-4630-8450-5e4e73e5e1ea) |
[ABW-3019]: https://radixdlt.atlassian.net/browse/ABW-3019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3019] AccountDetails UI fixes

RadixWallet/Core/DesignSystem/Components/Thumbnails.swift
Jira ticket: [ABW-3018](https://radixdlt.atlassian.net/browse/ABW-3018)
Changed loading shimmer background colour.
[ABW-3018]: https://radixdlt.atlassian.net/browse/ABW-3018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3018] AccountDetails - NFT key image loading shimmer background colour

Aux/Config/Common.xcconfig
=> 1.5.2 version bump

Aux/Config/Common.xcconfig, RadixWallet/Features/TransactionReviewFeature/TransactionReview+Sections.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewDapps/TransactionReviewDapps+View.swift
See discussion: https://rdxworks.slack.com/archives/C031A0V1A1W/p1712676427871339
=> Fix: Remove "Unauthorized" label

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
swift-custom-dump is transient dependency, had to pin in Package.resolved.
Fixes the build error in Release mode - https://github.com/pointfreeco/swift-custom-dump/pull/108
=> custom-dump version bump

Aux/Config/Common.xcconfig
=> 1.6.0 version bump

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Core/SargonExtensions/IntoSargon+Bridge.swift
Bump Sargon to a version which builds for `RELEASE`.
=> Bump Sargon to version which works under RELEASE.

RadixWallet.xcodeproj/project.pbxproj
[Slack thread](https://rdxworks.slack.com/archives/C03QFAWBRNX/p1714138085397749)
=> Pin Swift Sargon to 0.6.33

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/SecureStorageClient/SecureStorageClient+Live.swift, RadixWallet/Features/DebugInspectProfile/DebugInspectProfile.swift, RadixWalletTests/Clients/ProfileStoreTests/ProfileStoreTests.swift
Bumps Sargon to `0.7.4` - containing github.com/radixdlt/sargon/119 changes - which removes conformance to `Codable` on `Profile` since it is too slow.
=> Profile Not `Codable`

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Use latest version of Sargon with checksum optimization.
=> Bump Sargon

RadixWallet/Clients/AccountsClient/AccountsClient+Test.swift, RadixWallet/Clients/MnemonicClient/MnemonicClient+Test.swift
=> Fix RELEASE builds.

RadixWallet/Clients/DeviceFactorSourceClient/DeviceFactorSourceClient+Interface.swift, RadixWallet/Clients/DeviceFactorSourceClient/DeviceFactorSourceClient+Live.swift, RadixWallet/Clients/DeviceFactorSourceClient/DeviceFactorSourceClient+Test.swift, RadixWallet/Clients/SecurityCenterClient/SecurityCenterClient+Interface.swift, RadixWallet/Clients/SecurityCenterClient/SecurityCenterClient+Live.swift
- Refactor problem3 logic check
- https://radixdlt.atlassian.net/browse/ABW-3334
=> Refactor SecurityCenter.problem3 logic

RadixWallet/Clients/DappInteractionClient/DappInteractionClient+Live.swift, RadixWallet/Clients/RadixConnectClient/RadixConnectClient+Interface.swift, RadixWallet/Clients/RadixConnectClient/RadixConnectClient+Live.swift, RadixWallet/Clients/RadixConnectClient/RadixConnectClient+Test.swift, RadixWallet/Features/CreateAccount/Coordinator/CreateAccountCoordinator+Reducer.swift, RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift, RadixWallet/Features/OnboardingFeature/Coordinator/OnboardingCoordinator+Reducer.swift, RadixWallet/Features/ProfileBackupsFeature/RestoreProfileFromBackup/Coordinator/RestoreProfileFromBackupCoordinator.swift
Fixes the issue when P2P links were not connected after creating a new profile.
=> [CAP-36] Fix P2P links connection

RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Features/AccountDetailsFeature/Coordinator/AccountDetails+Reducer.swift, RadixWallet/Features/AccountDetailsFeature/Coordinator/AccountDetails+View.swift, RadixWallet/Features/AssetTransferFeature/Components/TransferAccountList/TransferAccountList+Reducer.swift, RadixWallet/Features/AssetTransferFeature/Components/TransferAccountList/TransferAccountList+View.swift, RadixWallet/Features/AssetsFeature/AssetsView+Reducer.swift, RadixWallet/Features/AssetsFeature/AssetsView+View.swift, RadixWallet/Features/AssetsFeature/Components/FungibleAssetList/Components/Details/FungibleTokenDetails+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/FungibleAssetList/Components/Section/FungibleAssetListSection+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/FungibleAssetList/FungibleAssetList+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/FungibleAssetList/FungibleAssetList+View.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Details/NonFungibleTokenDetails+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/NonFungibleAssetList+Reducer.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/NonFungibleAssetList+View.swift, RadixWallet/Features/AssetsFeature/Components/PoolUnitsList/PoolUnitsList+View.swift, RadixWallet/Features/AssetsFeature/Components/PoolUnitsList/PoolUnitsList.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/StakeUnitList+View.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/StakeUnitList.swift, RadixWallet/Features/DappsAndPersonas/DappDetails/DappDetails.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift
Jira ticket: [ABW-3092](https://radixdlt.atlassian.net/browse/ABW-3092?atlOrigin=eyJpIjoiOWI1OGY4Y2FiZGUxNDgxYWE4YTNlZGE0MWQ4Y2JjYzMiLCJwIjoiaiJ9)
This PR solves the presentation bug shown on first modal presentation of any asset details.
| UX Before | UX After |
| - | - |
| <video src=https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/62f09320-beb7-4f01-8d23-b61e0d3a579f> | <video src=https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/337ce40c-92ab-4cc6-966d-7b6b70592d30> |
[ABW-3092]: https://radixdlt.atlassian.net/browse/ABW-3092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3092] Fix Asset Details auto dismissal bug

RadixWallet/Clients/CacheClient/CacheClient+Interface.swift
Jira: https://radixdlt.atlassian.net/browse/ABW-3388
Fixed misplaced folder root
https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/ef370c9e-6428-4203-b7e1-80619e4810e4
=> CacheClient - Fix misplaced root

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
By bumping Sargon to 1.0.7, see relevant Sargon PR:  https://github.com/radixdlt/sargon/pull/153
=> Fix ISO8601 and 12/24 hour date crash bug

RadixWallet/Clients/ProfileStore/ProfileStore.swift
Jira ticket: [ABW-3390](https://radixdlt.atlassian.net/browse/ABW-3390)
Fixes the migration message issue that occurs during app updates by saving the profile after checking for legacy P2P links.
[ABW-3390]: https://radixdlt.atlassian.net/browse/ABW-3390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3390] Fix cap36 migration message

RadixWallet/Clients/SecurityCenterClient/SecurityCenterClient+Interface.swift
Replace hardcoded String with localized one
=> Use L10n String for problem3

Aux/Config/Common.xcconfig
=> 1.6.1 version bump

Aux/Config/Common.xcconfig
=> 1.7.1 Bump

Aux/Config/Common.xcconfig
Bump version to 1.8.0 before merging 1.8.0 related work, so all of the builds have 1.8.0 version
=> Bump to 1.8.0

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/GatewaysClient/GatewaysClient+Interface.swift, RadixWallet/Clients/GatewaysClient/GatewaysClient+Live.swift, RadixWallet/Clients/GatewaysClient/GatewaysClient+Test.swift, RadixWallet/Features/GatewaySettingsFeature/Children/AddNewGateway/AddNewGateway+Reducer.swift, RadixWalletTests/Features/GatewaySettingsFeatureTests/GatewaySettingsFeatureTests.swift
Depends on https://github.com/radixdlt/sargon/pull/182
Instead of checking ourselves if a Gateway with a given URL already exists, we will do it on Sargon (that considers the case of same with URL but with/without `/` at the end).
=> Check with Sargon if Gateway is already added

RadixWallet/Features/NewConnectionFeature/Coordinator/NewConnection+View.swift
https://radixdlt.atlassian.net/browse/ABW-3588
Fixed top spacing:
=> Fix New Connector spacing

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Bump to bring in latest changes
=> Bump Sargon to latest version

RadixWallet/Clients/AppEventsClient/AppEventsClient+Interface.swift, RadixWallet/Clients/HomeCardsClient/HomeCardsClient+Live.swift, RadixWallet/Features/OnboardingFeature/Coordinator/OnboardingCoordinator+Reducer.swift
This PR indicates Sargon after wallet restoration so we don't show Home cards for such session.
Check before/after videos on Slack
=> Do not show Home cards after Wallet restored

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Bump to bring in latest changes for the next release.
=> Bump Sargon to 1.0.30

Aux/Config/Common.xcconfig
=> 1.8.1 version bump

RadixWallet/Features/CreateAccount/Children/NewAccountCompletion/NewAccountCompletion+View.swift
Jira ticket: [ABW-3657](https://radixdlt.atlassian.net/browse/ABW-3657)
Makes account address tappable on Congratulations screen after creating a new account
[ABW-3657]: https://radixdlt.atlassian.net/browse/ABW-3657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3657] Make account address tappable after creating an account

Aux/Config/Common.xcconfig
Bump version for the next release
=> 1.8.3 version bump

RadixWallet/Core/DesignSystem/Components/CloseButton.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionFlow+View.swift, RadixWallet/Features/DisplayEntitiesControlledByMnemonic/DisplayEntitiesControlledByMnemonic+View.swift, RadixWallet/Features/TransactionReviewFeature/CustomizeFees/CustomizeFees+View.swift, RadixWallet/Features/TransactionReviewFeature/CustomizeFees/CustomizeFees.swift, RadixWallet/Features/TransactionReviewFeature/SelectFeePayer/SelectFeePayer+View.swift, RadixWallet/Features/TransactionReviewFeature/SelectFeePayer/SelectFeePayer.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewNetworkFee/TransactionReviewNetworkFee+View.swift, RadixWalletTests/Features/TransactionReviewFeatureTests/CustomizeFeePayerTests.swift
Jira tickets:
[ABW-3223](https://radixdlt.atlassian.net/browse/ABW-3223)
[ABW-3226](https://radixdlt.atlassian.net/browse/ABW-3226)
[ABW-3250](https://radixdlt.atlassian.net/browse/ABW-3250)
[ABW-2655](https://radixdlt.atlassian.net/browse/ABW-2655)
Fixes some minor, mostly visual issues. Some minor cleanup along the way.
[ABW-3223]: https://radixdlt.atlassian.net/browse/ABW-3223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ABW-3226]: https://radixdlt.atlassian.net/browse/ABW-3226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ABW-3250]: https://radixdlt.atlassian.net/browse/ABW-3250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ABW-2655]: …
=> Misc small fixes

RadixWallet/Features/AssetsFeature/Components/FungibleAssetList/Components/Details/FungibleTokenDetails+View.swift, RadixWallet/Features/AssetsFeature/Components/HelperViews/AssetResourceDetails.swift, RadixWallet/Features/AssetsFeature/Components/NonFungibleAssetList/Components/Details/NonFungibleTokenDetails+View.swift, RadixWallet/Features/AssetsFeature/Components/PoolUnitsList/Components/PoolUnitDetails+View.swift, RadixWallet/Features/AssetsFeature/Components/StakeUnitList/Components/LSUDetails+View.swift
Jira ticket: [ABW-2700](https://radixdlt.atlassian.net/browse/ABW-2700)
Shows the divisibility on fungible token details.
[ABW-2700]: https://radixdlt.atlassian.net/browse/ABW-2700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-2700] Show divisibility on details view

RadixWallet/Core/DesignSystem/Components/WarningView.swift, RadixWallet/Features/TransactionReviewFeature/CustomizeFees/CustomizeFees+View.swift, RadixWallet/Features/TransactionReviewFeature/CustomizeFees/CustomizeFees.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewNetworkFee/TransactionReviewNetworkFee+View.swift
I accidentally merged some changes from [#1282](https://github.com/radixdlt/babylon-wallet-ios/pull/1282) along with  [#1281](https://github.com/radixdlt/babylon-wallet-ios/pull/1281), this PR reverts them.
=> Reverting premature changes

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/AuthorizedDappsClient/AuthorizedDappsClient+Interface.swift, RadixWallet/Core/DesignSystem/ToggleView.swift, RadixWallet/Features/CreateAccount/Children/NameAccount/NameAccount+View.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionFlow+View.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionFlow.swift, RadixWallet/Features/DappsAndPersonas/DappDetails/DappDetails+View.swift, RadixWallet/Features/DappsAndPersonas/DappDetails/DappDetails.swift, RadixWalletTests/ProfileTests/EntitiesHidingTests.swift
Jira ticket: [ABW-3755](https://radixdlt.atlassian.net/browse/ABW-3755)
This PR allows user to view/hide deposit claims for any given dapp.
[Video](https://drive.google.com/file/d/1l9wF1RVyZqE9bDaqTQ2Tq5nIUxBcKjUS/view?usp=sharing)
[ABW-3755]: https://radixdlt.atlassian.net/browse/ABW-3755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3755] Dapp deposits claim setting

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/AccountPortfoliosClient/AccountPortfoliosClient+Live.swift, RadixWallet/Clients/AccountPortfoliosClient/AccountPortfoliosClient+State.swift, RadixWallet/Clients/AppPreferencesClient/AppPreferencesClient+Interface.swift, RadixWallet/Clients/OnLedgerEntitiesClient/Helpers/OnLedgerEntitiesClient+ComplexTypes.swift, RadixWallet/Clients/ProfileStore/ProfileStore+AsyncSequence+Updates.swift, RadixWallet/Clients/ProfileStore/ProfileStore.swift, RadixWallet/Clients/ResourcesVisibilityClient/ResourcesVisibilityClient+Interface.swift, RadixWallet/Clients/ResourcesVisibilityClient/ResourcesVisibilityClient+Live.swift, RadixWallet/Clients/ResourcesVisibilityClient/ResourcesVisibilityClient+Test.swift, RadixWallet/Features/AssetsFeature/Components/HideResource/HIdeResource.swift, RadixWallet/Features/SettingsFeature/Preferences/HiddenAssets/HiddenAssets.swift, RadixWallet/MIGRATE_TO_SARGON/Stage2/Atoms/Stage2MigrateToSargon+ProfileNetwork.swift, RadixWallet/MIGRATE_TO_SARGON/Stage2/Profile/Profile/Profile+Account+Add.swift, RadixWalletTests/ProfileTests/EntitiesHidingTests.swift, RadixWalletTests/TestExtensions/TestUtils.swift
Jira ticket: [ABW-3771](https://radixdlt.atlassian.net/browse/ABW-3771)
This PR uses latest Sargon version where `ResourcePreferences` are now located under `ProfileNetwork`. This prevents mixing resource from different networks, which would end up in a failure GW response when fetching their details.
[ABW-3771]: https://radixdlt.atlassian.net/browse/ABW-3771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3771] Fix issues when hiding/unhiding resources

RadixWallet/Features/AppFeature/Overlay/InfoLinkSheet+Reducer.swift, RadixWallet/Features/AppFeature/Overlay/InfoLinkSheet+View.swift, RadixWallet/Features/SettingsFeature/Preferences/HiddenEntities/HiddenEntities+View.swift
Jira ticket: [ABW-3783](https://radixdlt.atlassian.net/browse/ABW-3783)
Jira ticket: [ABW-3784](https://radixdlt.atlassian.net/browse/ABW-3784)
Jira ticket: [ABW-3787](https://radixdlt.atlassian.net/browse/ABW-3787)
- Show tokens icon for `GlossaryItem.tokens` (instead of `.radixnetwork`)
- Adds bottom padding to view
- Fixes aspect ratio for images
- Fix padding for `Unhide` button on large accounts
[ABW-3783]: https://radixdlt.atlassian.net/browse/ABW-3783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ABW-3784]: https://radixdlt.atlassian.net/browse/ABW-3784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ABW-3787]: https://radixdlt.atlassian.net/browse/ABW-3787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
=> Info view + Hidden Accounts UI fixes

RadixWallet/Features/AssetsFeature/Components/HelperViews/AssetBehaviorsView.swift, RadixWallet/Features/AssetsFeature/Components/HelperViews/EmptyAssetListView.swift, RadixWallet/Features/CreatePersona/Children/Introduction/IntroductionToPersonas+View.swift, RadixWallet/Features/DappsAndPersonas/AuthorizedDApps/AuthorizedDApps+View.swift, RadixWallet/Features/DappsAndPersonas/Personas/Child/List/PersonaList+View.swift, RadixWallet/Features/EditPersonaFeature/EditPersona/EditPersona+View.swift, RadixWallet/Features/GatewaySettingsFeature/GatewaySettings+View.swift, RadixWallet/Features/ScanQR/Children/ScanQR/ScanQR+View.swift, RadixWallet/Features/SettingsFeature/Preferences/DefaultDepositGuarantees/DefaultDepositGuarantees+View.swift, RadixWallet/Features/TransactionReviewFeature/CustomizeFees/CustomizeFees+View.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReviewGuarantees/TransactionReviewGuarantees+View.swift
Jira ticket: [ABW-3793](https://radixdlt.atlassian.net/browse/ABW-3793)
Uses titles under `L10n.InfoLink.Title` for every `InfoButton`.
[ABW-3793]: https://radixdlt.atlassian.net/browse/ABW-3793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3793] Update InfoButton titles

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/AccountLockersClient/AccountLockersClient+Live.swift, RadixWallet/Clients/OnLedgerEntitiesClient/Helpers/OnLedgerEntitiesClient+CreateEntity.swift, RadixWallet/Clients/OnLedgerEntitiesClient/OnLedgerEntitiesClient+Interface.swift, RadixWallet/Clients/OnLedgerEntitiesClient/OnLedgerEntitiesClient+Live.swift, RadixWallet/Core/SharedModels/Assets/OnLedgerEntity.swift, RadixWallet/Features/TransactionReviewFeature/TransactionReview+Sections.swift
Jira ticket: [ABW-3796](https://radixdlt.atlassian.net/browse/ABW-3796)
This PR allows showing `USING DAPPS` section on Transaction Review for account locker claims.
[Demo](https://drive.google.com/file/d/1VWDZazJxXww9kMSpoq8dANUh-FDhud87/view?usp=sharing)
[ABW-3796]: https://radixdlt.atlassian.net/browse/ABW-3796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3796] Show Using Dapps section on account locker claims

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Core/DesignSystem/Components/AppTextField.swift, RadixWallet/Features/ImportMnemonic/ImportMnemonic+View.swift, RadixWallet/Features/ImportMnemonic/ImportWord/ImportMnemonicWord+View.swift
Jira ticket: [ABW-3790](https://radixdlt.atlassian.net/browse/ABW-3790)
This PR fixes a bug happening only on release mode, where the keyboard would be automatically dismissed when entering seed phrase.
1. Select `Radix Wallet PROD` scheme
2. Archive app
3. On Organizer `Distribute App` > `Release Testing`
4. Export and drag `.ipa` file to your device
5. Recover wallet from Backup to enter seed phrase
6. Verify you have no issues as shown in JIRA video.
[ABW-3790]: https://radixdlt.atlassian.net/browse/ABW-3790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3790] Fix auto dismiss keyboard when entering Seed Phrase

Aux/Config/Common.xcconfig
=> 1.10.0 bump

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Jira ticket: [ABW-3803](https://radixdlt.atlassian.net/browse/ABW-3803)
Updates the dependency to `123.0.0`
[ABW-3803]: https://radixdlt.atlassian.net/browse/ABW-3803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ABW-3803] Update webRTC to 123.0.0

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/PreAuthorizationClient/PreAuthorizationClient+Interface.swift, RadixWallet/Clients/PreAuthorizationClient/PreAuthorizationClient+Live.swift, RadixWallet/Features/PreAuthorizationReview/PreAuthorizationReview.swift
Brings in - https://github.com/radixdlt/sargon/pull/278
=> Bump sargon to get tx review v2

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/DappInteractionClient/DappInteractionClient+Live.swift, RadixWallet/Clients/PreAuthorizationClient/PreAuthorizationClient+Interface.swift, RadixWallet/Clients/PreAuthorizationClient/PreAuthorizationClient+Live.swift, RadixWallet/Clients/ProfileStore/ProfileStore.swift, RadixWallet/Core/SharedModels/P2P/Dapp/Models/WalletInteraction+PreviewValue.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionModels.swift, RadixWallet/Features/PreAuthorizationReview/PreAuthorizationReview.swift
Bumps Sargon and updates handling of Proof of Ownership, which is now included in authorized requests.
[Sample dApp to test](https://dn5h1ocyofa5a.cloudfront.net/)
=> Update Proof of Ownership logic

Aux/Config/Common.xcconfig
=> Bump version to 1.11.0

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/CloudBackupClient/CloudBackupClient+Live.swift, RadixWallet/Clients/ProfileStore/ProfileStore.swift, RadixWalletTests/Clients/TransactionClientTests/TransactionClientTests.swift, RadixWalletTests/Features/SplashFeatureTests/SplashFeatureTests.swift
Brings in https://github.com/radixdlt/sargon/pull/303.
Target branch - 1.11.1-hotfix
=> Profle claim fix

Aux/Config/Common.xcconfig, RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Features/InteractionReview/Sections/Sections+ManifestSummary.swift, RadixWallet/Features/SplashFeature/Splash.swift, RadixWallet/SargonExtensions/SargonSecureStorageDriver.swift
Display raw manifest if the Pre-Auth manifest is not classified as GeneralSubintent.
https://drive.google.com/file/d/1bywGYgk8GTV6YxxEknSk2OyizHW8N0mu/view
=> GeneralSubintent manifest class

RadixWallet/Features/SettingsFeature/Troubleshooting/Troubleshooting.swift
As requested by Adam [here](https://rdxworks.slack.com/archives/CSTPKUDUK/p1736251053645099)
=> Update discord link

RadixWallet/Features/AppFeature/Overlay/InfoLinkSheet+Reducer.swift, RadixWallet/Features/ShieldSetup/PickShieldBuilderSeedingFactors/Children/PickShieldBuilderSeedingFactors+Reducer.swift, RadixWallet/Features/ShieldSetup/RolesSetup/Children/PrimaryRoleSetup/PrimaryRoleSetup+View.swift, RadixWallet/Features/ShieldSetup/RolesSetup/Children/RecoveryRoleSetup/RecoveryRoleSetup+Reducer.swift, RadixWallet/Features/ShieldSetup/RolesSetup/Children/RecoveryRoleSetup/RecoveryRoleSetup+View.swift
Updates related to Shield Setup:
- Build unsafe shield confirmation
- Not enough factors warning
- `infoLink_glossary_emergencyfallback` string
[video](https://rdxworks.slack.com/archives/C03QFAWBRNX/p1738062751393369?thread_ts=1738062732.962639&cid=C03QFAWBRNX)
=> Shield Setup updates

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/FactorSourcesClient/FactorSourcesClient+Live.swift, RadixWallet/Core/FeaturePrelude/FactorSourceCard/FactorSourceCard+DataSource.swift, RadixWallet/Core/FeaturePrelude/FactorSourceCard/FactorSourceCard.swift, RadixWallet/Features/DappInteractionFeature/Coordinator/DappInteractionFlow.swift, RadixWallet/Features/SecurityCenterFeature/SecurityFactors/FactorSourcesList+View.swift, RadixWallet/Features/SecurityCenterFeature/SecurityFactors/FactorSourcesList.swift, RadixWallet/Features/ShieldSetup/AddShieldBuilderSeedingFactors/AddShieldBuilderSeedingFactorsCoordinator.swift, RadixWallet/Features/ShieldSetup/PickShieldBuilderSeedingFactors/Children/PickShieldBuilderSeedingFactors+View.swift, RadixWallet/Features/ShieldSetup/RolesSetup/Children/RecoveryRoleSetup/RecoveryRoleSetup+Reducer.swift, RadixWallet/Features/ShieldSetup/RolesSetup/Children/RecoveryRoleSetup/RecoveryRoleSetup+View.swift
Fixes after latest breaking changes on Sargon (removal of `SecurityQuestions` & `TrustedContact` factor sources).
=> Update Sargon to latest version

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/release.yml, .gitignore
Jira ticket: [paste link here](https://radixdlt.atlassian.net/browse/DO-2800)
Complements / depends on / relates to #link to other PR
Refactor of secrets on CI/CD
=> ci: Refactor CI/CD secrets

RadixWallet.xcodeproj/project.pbxproj, RadixWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RadixWallet/Clients/DeviceFactorSourceClient/DeviceFactorSourceClient+Live.swift, RadixWallet/Core/FeaturePrelude/FeatureReducer.swift, RadixWallet/Features/DerivePublicKeys/DerivePublicKeys.swift, RadixWallet/Features/SecurityCenterFeature/SecurityFactors/FactorSourceDetail+View.swift, RadixWallet/Features/SecurityCenterFeature/SecurityFactors/FactorSourceDetail.swift, RadixWallet/Features/Signing/Signing.swift, RadixWallet/Features/SpotCheck/SpotCheck.swift
- Updates the `FactorSource` last used date every time the user signs, derives public keys or performs a spot check with the given factor source.
- Support public keys derivation for `OffDeviceMnemonicFactorSource`.
[Link](https://drive.google.com/file/d/1T2Nf2V3e03MzEgz8_LfRBQvdcE-YonOL/view?usp=sharing)
=> Update Factor Source last used + support derivation for `offDeviceMnemonic`

RadixWallet/Clients/DAppsDirectoryClient/DAppsDirectoryClient+Interface.swift, RadixWallet/Clients/DAppsDirectoryClient/DAppsDirectoryClient+Live.swift, RadixWallet/Clients/DAppsDirectoryClient/DAppsDirectoryClient+Test.swift, RadixWallet/Features/DApps/DAppsDirectory.swift
Hookup properly pull to refresh.
=> Fix dApp directory pull to refresh

Aux/Config/Common.xcconfig, RadixWallet/Clients/TransactionClient/TransactionClient+Interface.swift, RadixWallet/Clients/TransactionClient/TransactionClient+Live.swift, RadixWallet/Core/Resources/Generated/L10n.generated.swift, RadixWallet/Core/Resources/Resources/en.lproj/Localizable.strings, RadixWallet/Features/AssetTransferFeature/Components/ChooseRecipient/ChooseTransferRecipient+Reducer.swift, RadixWallet/Features/AssetTransferFeature/Components/ChooseRecipient/ChooseTransferRecipient+View.swift, RadixWallet/Features/TransactionReviewFeature/SelectFeePayer/SelectFeePayer.swift, RadixWalletTests/Clients/TransactionClientTests/TransactionClientTests.swift
- Handle non-lowercase domain input properly.
- Fix fee payer resolution.
=> 1.15.1 Hotfix
